package content

// detailsIT is the Italian rich content + voice for every exercise.
var detailsIT = map[string]Detail{
	// ---- Riscaldamento ----
	"W01": {
		Desc:    "Un inizio dolce: respirazione, allungamento della colonna e postura.",
		HowTo:   []string{"Stai in piedi, piedi alla larghezza dei fianchi.", "Inspirando, allungati dolcemente verso l'alto dalla sommità del capo.", "Puoi alzare le braccia lateralmente.", "Espirando, abbassa le spalle e rilassa il collo."},
		Correct: []string{"Piedi ben saldi a terra.", "Le spalle non salgono alle orecchie.", "Collo lungo.", "Respirazione calma."},
		Wrong:   []string{"Inclinare la testa indietro.", "Inarcare troppo la zona lombare.", "Alzare le spalle.", "Trattenere il respiro."},
		Voice:   Voice{Start: "Stai dritto. Respira con calma.", Mid: []string{"Allungati dalla sommità del capo."}, Finish: "Spalle giù. Continua."},
	},
	"W02": {
		Desc:    "Mobilizzare il collo prima dell'allenamento.",
		HowTo:   []string{"Stai in piedi.", "Gira la testa lentamente a destra.", "Torna al centro.", "Gira la testa a sinistra."},
		Correct: []string{"Movimento lento.", "Le spalle restano basse.", "Il tronco non ruota.", "Ampiezza comoda."},
		Wrong:   []string{"Movimenti bruschi.", "Inclinare la testa indietro.", "Alzare le spalle.", "Allungare il collo fino al dolore."},
		Voice:   Voice{Start: "Giriamo la testa.", Mid: []string{"Dolce, senza scatti."}, Finish: "Testa al centro."},
	},
	"W03": {
		Desc:    "Riscaldare le articolazioni delle spalle e la parte alta della schiena.",
		HowTo:   []string{"Stai in piedi.", "Alza un po' le spalle.", "Portale indietro.", "Abbassale e ripeti il cerchio."},
		Correct: []string{"Le spalle si muovono fluide.", "Braccia rilassate.", "Il collo resta libero.", "Tronco stabile."},
		Wrong:   []string{"Scrollare le spalle.", "Incurvarsi.", "Tendere il collo.", "Ampiezza troppo grande."},
		Voice:   Voice{Start: "Cerchi con le spalle, indietro.", Mid: []string{"Collo libero."}, Finish: "Abbassa le spalle."},
	},
	"W04": {
		Desc:    "Più mobilità per spalle e parte alta della schiena.",
		HowTo:   []string{"Stai in piedi.", "Ruota le spalle in avanti.", "Tieni il collo libero.", "Non dondolare il tronco."},
		Correct: []string{"Movimento controllato.", "Spalle senza tensione.", "Respirazione regolare.", "Il tronco non dondola."},
		Wrong:   []string{"Spalle alle orecchie.", "Movimento brusco.", "Arrotondare la schiena.", "Trattenere il respiro."},
		Voice:   Voice{Start: "Cerchi in avanti.", Mid: []string{"Non tendere il collo."}, Finish: "Rilassa le spalle."},
	},
	"W05": {
		Desc:    "Riscaldare spalle, deltoidi e parte alta della schiena.",
		HowTo:   []string{"Braccia ai lati, all'altezza delle spalle.", "Piccoli cerchi in avanti.", "Tieni le spalle basse.", "Non trattenere il respiro."},
		Correct: []string{"Cerchi piccoli.", "Braccia all'altezza delle spalle.", "Collo rilassato.", "Il tronco non dondola."},
		Wrong:   []string{"Grandi mulinelli.", "Spalle alle orecchie.", "Inarcare la schiena.", "Tendere il collo."},
		Voice:   Voice{Start: "Braccia ai lati. Cerchi piccoli.", Mid: []string{"Spalle giù."}, Finish: "Abbassa le braccia."},
	},
	"W06": {
		Desc:    "Riscaldare le spalle e gli stabilizzatori della scapola.",
		HowTo:   []string{"Braccia ai lati.", "Piccoli cerchi all'indietro.", "Non alzare le spalle.", "Tieni il tronco dritto."},
		Correct: []string{"Movimento corto.", "Spalle basse.", "Le scapole lavorano dolcemente.", "Respirazione calma."},
		Wrong:   []string{"Scatti.", "Mulinelli ampi.", "Incurvarsi.", "Tendere il collo."},
		Voice:   Voice{Start: "Cerchi all'indietro.", Mid: []string{"Ampiezza piccola."}, Finish: "Rilassa le braccia."},
	},
	"W07": {
		Desc:    "Attiva la parte alta della schiena e apre il petto.",
		HowTo:   []string{"Stai in piedi.", "Porta le braccia un po' indietro.", "Avvicina dolcemente le scapole.", "Torna in posizione neutra."},
		Correct: []string{"Il petto si apre.", "Spalle basse.", "Le scapole lavorano dolcemente.", "La schiena non si inarca."},
		Wrong:   []string{"Spezzare la schiena all'indietro.", "Alzare il mento.", "Tirare le braccia.", "Alzare le spalle."},
		Voice:   Voice{Start: "Apriamo il petto.", Mid: []string{"Scapole dolcemente indietro."}, Finish: "Torna al centro."},
	},
	"W08": {
		Desc:    "Mobilità dolce per la colonna dorsale e il tronco.",
		HowTo:   []string{"Stai in piedi.", "Ruota il tronco a destra.", "Torna al centro.", "Ruota il tronco a sinistra."},
		Correct: []string{"Il movimento parte dal tronco.", "Bacino quasi fermo.", "I piedi non ruotano.", "Ampiezza comoda."},
		Wrong:   []string{"Ruotare il tronco con bruschezza.", "Torcere le ginocchia.", "Scuotere i piedi.", "Cadere all'indietro."},
		Voice:   Voice{Start: "Rotazioni del tronco.", Mid: []string{"Piedi saldi."}, Finish: "Torna al centro."},
	},
	"W09": {
		Desc:    "Riscalda l'anca e la parte posteriore della gamba; insegna a piegarsi senza arrotondare la schiena.",
		HowTo:   []string{"Stai in piedi, ginocchia leggermente morbide.", "Spingi il bacino all'indietro.", "Piega il tronco con la schiena piatta.", "Risali."},
		Correct: []string{"Schiena piatta.", "Il movimento parte dall'anca.", "Ginocchia leggermente morbide.", "Il collo segue la linea della schiena."},
		Wrong:   []string{"Arrotondare la schiena.", "Trasformarlo in uno squat.", "Forzare per arrivare in basso.", "Alzare la testa."},
		Voice:   Voice{Start: "Bacino indietro, schiena piatta.", Mid: []string{"Non arrotondare la schiena."}, Finish: "Raddrizzati con calma."},
	},
	"W10": {
		Desc:    "Riscaldare piedi, polpacci ed equilibrio.",
		HowTo:   []string{"Stai in piedi.", "Sollevati sulle punte.", "Tieni un istante.", "Scendi lentamente."},
		Correct: []string{"Corpo verticale.", "Movimento fluido.", "Piedi stabili.", "Le ginocchia non cadono verso l'interno."},
		Wrong:   []string{"Lasciar cadere i talloni.", "Dondolare.", "Cadere sul bordo esterno del piede.", "Fare scatti."},
		Voice:   Voice{Start: "Sollevati sulle punte.", Mid: []string{"Scendi lentamente."}, Finish: "Piedi stabili."},
	},

	// ---- Blocco principale ----
	"M01": {
		Desc:      "Esercizio di base per petto, tricipiti, spalle e tronco.",
		HowTo:     []string{"Mani sotto le spalle o un po' più larghe.", "Gambe distese, corpo dritto.", "Scendi lentamente.", "Spingi verso l'alto senza scatti."},
		Correct:   []string{"Corpo dritto.", "Addome contratto.", "I gomiti non si aprono del tutto.", "Movimento controllato."},
		Wrong:     []string{"Affossare la zona lombare.", "Alzare il bacino.", "Lasciarsi cadere.", "Aprire i gomiti a 90°."},
		Breathing: "Inspira scendendo, espira salendo.",
		Voice:     Voice{Start: "Corpo dritto. Iniziamo.", Mid: []string{"Addome contratto.", "Gomiti non troppo aperti."}, Finish: "Fatto. Rilassa le spalle."},
	},
	"M02": {
		Desc:      "Una variante di piegamento più orientata ai tricipiti.",
		HowTo:     []string{"Mani circa sotto le spalle.", "Gomiti indietro, vicini al corpo.", "Scendi lentamente.", "Spingi senza scatti."},
		Correct:   []string{"Corpo dritto.", "I gomiti non si aprono.", "Spalle senza tensione.", "Polsi senza dolore."},
		Wrong:     []string{"Mani troppo vicine.", "Piegare i polsi.", "Aprire i gomiti.", "Perdere la linea del corpo."},
		Breathing: "Inspira scendendo, espira salendo.",
		Safety:    "Se gomiti o polsi fanno male, passa al piegamento normale con meno ripetizioni.",
		Voice:     Voice{Start: "Piegamento stretto. Gomiti vicini.", Mid: []string{"Non premere sui polsi.", "Corpo dritto."}, Finish: "Bene. Rilassa le spalle."},
	},
	"M03": {
		Desc:      "Piegamento con controllo nel punto più basso.",
		HowTo:     []string{"Mettiti in posizione di piegamento.", "Scendi lentamente.", "Tieni 1 secondo.", "Spingi verso l'alto."},
		Correct:   []string{"Pausa controllata.", "Il corpo non si affossa.", "Gomiti sotto controllo.", "Nessuna caduta."},
		Wrong:     []string{"Lasciarsi cadere.", "Rilassarsi in basso.", "Trattenere il respiro.", "Inarcare la zona lombare."},
		Breathing: "Inspira, breve pausa, espira salendo.",
		Voice:     Voice{Start: "Scendi lentamente. Tieni in basso.", Mid: []string{"Non cadere, controlla.", "La zona lombare non si affossa."}, Finish: "Ottimo. Riposa."},
	},
	"C01": {
		Desc:    "Esercizio per gli addominali e il controllo del bacino.",
		HowTo:   []string{"Sdraiati supino.", "Premi la zona lombare contro il tappetino.", "Solleva le gambe.", "Incrocia con ampiezza ridotta."},
		Correct: []string{"Schiena sul tappetino.", "Gambe non troppo basse.", "Collo rilassato.", "Movimento controllato."},
		Wrong:   []string{"Staccare la schiena.", "Abbassare troppo le gambe.", "Tirare il collo in avanti.", "Mulinelli bruschi."},
		Safety:  "Se la schiena si stacca, passa ai Toe taps o al Dead bug.",
		Voice:   Voice{Start: "Forbici. Schiena premuta.", Mid: []string{"Alza le gambe se tira la schiena.", "Collo rilassato."}, Last: "Cinque secondi.", Finish: "Abbassa le gambe piano."},
	},
	"C02": {
		Desc:      "Esercizio statico per addominali, spalle, glutei e stabilità del tronco.",
		HowTo:     []string{"Appoggiati sui gomiti e sulle punte dei piedi.", "Gomiti sotto le spalle.", "Contrai addome e glutei.", "Mantieni una linea del corpo dritta."},
		Correct:   []string{"Spalle sopra i gomiti.", "Il bacino non si affossa.", "Addome contratto.", "Sguardo a terra."},
		Wrong:     []string{"Affossare la zona lombare.", "Alzare il bacino come un tetto.", "Guardare avanti.", "Trattenere il respiro."},
		Breathing: "Inspira corto, espira lungo e calmo.",
		Voice:     Voice{Start: "Plank. Corpo in una linea.", Mid: []string{"Addome contratto.", "La schiena non si affossa."}, Last: "Cinque secondi.", Finish: "Appoggia le ginocchia."},
	},
	"C03": {
		Desc:    "Esercizio per gli addominali e il controllo della zona lombare.",
		HowTo:   []string{"Sdraiati supino.", "Premi la zona lombare contro il tappetino.", "Solleva le gambe.", "Brevi movimenti alternati su e giù."},
		Correct: []string{"Schiena stabile.", "Ampiezza ridotta.", "Gambe non troppo basse.", "Respirazione regolare."},
		Wrong:   []string{"Inarcare la zona lombare.", "Grandi mulinelli.", "Tendere il collo.", "Trattenere il respiro."},
		Safety:  "Se la schiena si stacca, alza le gambe o passa al Dead bug.",
		Voice:   Voice{Start: "Schiena premuta.", Mid: []string{"Ampiezza ridotta.", "Respira in modo regolare."}, Last: "Cinque secondi.", Finish: "Abbassa le gambe lentamente."},
	},
	"C04": {
		Desc:      "Esercizio sicuro per il core profondo e la stabilità.",
		HowTo:     []string{"Supino, braccia verso l'alto.", "Ginocchia a 90°.", "Abbassa lentamente braccio e gamba opposti.", "Torna e ripeti dall'altro lato."},
		Correct:   []string{"Schiena premuta.", "Movimento lento.", "Il tronco non dondola.", "Ampiezza sotto controllo."},
		Wrong:     []string{"Staccare la schiena.", "Andare veloce.", "Abbassare troppo la gamba.", "Perdere il controllo del bacino."},
		Breathing: "Espira distendendo braccio e gamba.",
		Voice:     Voice{Start: "Dead bug. Schiena premuta.", Mid: []string{"Muoviti lentamente.", "Il tronco non dondola."}, Finish: "Bene. Riporta le gambe."},
	},
	"C05": {
		Desc:    "Esercizio per gli addominali laterali e la stabilità.",
		HowTo:   []string{"Sdraiati su un fianco.", "Gomito sotto la spalla.", "Solleva il bacino.", "Tieni il corpo in una linea."},
		Correct: []string{"Gomito sotto la spalla.", "Bacino sollevato.", "Il corpo non si inclina.", "Collo neutro."},
		Wrong:   []string{"Lasciar cadere il bacino.", "Avvicinare la spalla all'orecchio.", "Ruotare il tronco verso il basso.", "Trattenere il respiro."},
		Safety:  "Se la spalla fa male, riduci il tempo della metà o fai il plank normale.",
		Voice:   Voice{Start: "Plank laterale. Gomito sotto la spalla.", Mid: []string{"Tieni il bacino alto.", "Collo libero."}, Last: "Cinque secondi.", Finish: "Scendi con dolcezza."},
	},
	"C06": {
		Desc:    "Esercizio di controllo per gli addominali; più dolce delle forbici.",
		HowTo:   []string{"Supino, gambe a 90°.", "Abbassa lentamente un tallone verso terra.", "Riporta la gamba.", "Ripeti con l'altra gamba."},
		Correct: []string{"La schiena non si stacca.", "Movimento lento.", "Bacino stabile.", "Il tallone sfiora il suolo."},
		Wrong:   []string{"Lasciar cadere la gamba.", "Inarcare la zona lombare.", "Muovere entrambe le gambe insieme.", "Affrettarsi."},
		Voice:   Voice{Start: "Toe taps. Lentamente.", Mid: []string{"Schiena sul tappetino.", "Tocco leggero."}, Finish: "Rilassa l'addome."},
	},
	"C07": {
		Desc:    "Esercizio statico per gli addominali e il controllo del tronco.",
		HowTo:   []string{"Supino, schiena premuta.", "Solleva un po' le spalle.", "Gambe piegate o un po' sollevate.", "Mantieni la posizione."},
		Correct: []string{"Schiena a terra.", "Addome contratto.", "Il collo non si protende.", "Senza trattenere il respiro."},
		Wrong:   []string{"Inarcare la zona lombare.", "Alzare il mento.", "Gambe troppo basse.", "Sopportare il dolore alla schiena."},
		Safety:  "Se la schiena tira, piega le ginocchia o passa al Dead bug.",
		Voice:   Voice{Start: "Hollow hold. Schiena premuta.", Mid: []string{"Respira in modo regolare.", "Se la schiena tira, piega le ginocchia."}, Last: "Cinque secondi.", Finish: "Abbassa spalle e gambe."},
	},
	"C08": {
		Desc:      "Plank breve e intenso con massima tensione del core.",
		HowTo:     []string{"Mettiti in plank sugli avambracci.", "Gomiti sotto le spalle.", "Contrai addome e glutei.", "Tira i gomiti verso le punte dei piedi."},
		Correct:   []string{"Forte tensione addominale.", "Glutei attivi.", "Corpo dritto.", "Respira senza bloccare."},
		Wrong:     []string{"Tenere come un plank molle.", "Affossare la zona lombare.", "Trattenere il respiro.", "Tenere troppo a lungo."},
		Breathing: "Respiri brevi, senza bloccare.",
		Safety:    "Se è troppo duro, plank normale di 45-60 secondi.",
		Voice:     Voice{Start: "Contrai addome e glutei.", Mid: []string{"Gomiti verso le punte.", "Tutto il corpo contratto."}, Last: "Cinque secondi.", Finish: "Appoggia le ginocchia."},
	},
	"B01": {
		Desc:    "Esercizio per la schiena, i glutei e la catena posteriore.",
		HowTo:   []string{"Sdraiati prono.", "Braccia avanti o lungo il corpo.", "Solleva un po' petto e gambe.", "Scendi con controllo."},
		Correct: []string{"Sollevamento piccolo.", "Il collo segue la linea della schiena.", "Glutei un po' attivi.", "Senza scatti."},
		Wrong:   []string{"Spezzare forte la schiena.", "Alzare la testa.", "Alzare troppo le gambe.", "Fare scatti."},
		Voice:   Voice{Start: "Barchetta. Sollevamento piccolo.", Mid: []string{"Collo neutro.", "Non spezzare la schiena."}, Finish: "Scendi con dolcezza."},
	},
	"B02": {
		Desc:    "Esercizio per la parte alta della schiena, le scapole e la spalla posteriore.",
		HowTo:   []string{"Sdraiati prono.", "Solleva un po' il petto o lascialo a terra.", "Porta le braccia ad arco sopra la testa.", "Riporta le braccia."},
		Correct: []string{"Collo rilassato.", "Le scapole lavorano.", "Ampiezza comoda.", "Senza sovraccaricare la schiena."},
		Wrong:   []string{"Alzare la testa.", "Inarcarsi troppo.", "Tirare le braccia.", "Spalle alle orecchie."},
		Voice:   Voice{Start: "Braccia ad arco. Testa giù.", Mid: []string{"Le scapole lavorano.", "Non tendere il collo."}, Finish: "Rilassa le braccia."},
	},
	"B03": {
		Desc:    "Tenuta statica per la schiena e i glutei.",
		HowTo:   []string{"Sdraiati prono.", "Solleva un po' petto e gambe.", "Mantieni la posizione.", "Respira in modo regolare."},
		Correct: []string{"Sollevamento moderato.", "Collo neutro.", "Glutei attivi.", "Respirazione regolare."},
		Wrong:   []string{"Alzare la testa.", "Inarcarsi forte.", "Trattenere il respiro.", "Sopportare il dolore alla schiena."},
		Safety:  "Se la schiena disturba, fai la Barchetta con meno ampiezza.",
		Voice:   Voice{Start: "Tieni la barchetta.", Mid: []string{"Respira in modo regolare.", "Collo lungo."}, Last: "Cinque secondi.", Finish: "Scendi con dolcezza."},
	},
	"B04": {
		Desc:    "Esercizio per la parte alta della schiena, le scapole e la spalla posteriore.",
		HowTo:   []string{"Sdraiati prono.", "Piega le braccia a forma di 'W'.", "Solleva un po' gomiti e mani.", "Avvicina le scapole e abbassa."},
		Correct: []string{"Movimento piccolo.", "Le scapole lavorano.", "La testa guarda a terra.", "Spalle lontane dalle orecchie."},
		Wrong:   []string{"Alzare la testa.", "Alzare troppo le braccia.", "Tendere il collo.", "Inarcare la zona lombare."},
		Voice:   Voice{Start: "Sollevamento a W. Scapole indietro.", Mid: []string{"Testa giù.", "Movimento piccolo."}, Finish: "Abbassa le braccia."},
	},
	"B05": {
		Desc:    "Esercizio per la parte alta della schiena, le spalle e il trapezio inferiore.",
		HowTo:   []string{"Sdraiati prono.", "Distendi le braccia in diagonale a forma di 'Y'.", "Solleva un po' le braccia da terra.", "Riabbassa."},
		Correct: []string{"Le braccia si alzano poco.", "Scapole basse e indietro.", "Collo neutro.", "Schiena tranquilla."},
		Wrong:   []string{"Oscillazione brusca.", "Alzare la testa.", "Spalle alle orecchie.", "Inarcarsi forte."},
		Voice:   Voice{Start: "Sollevamento a Y. Braccia in diagonale.", Mid: []string{"Spalle lontane dalle orecchie.", "Sollevamento piccolo."}, Finish: "Rilassa la schiena."},
	},
	"G01": {
		Desc:    "Esercizio per i glutei, la parte posteriore della gamba e la stabilità del bacino.",
		HowTo:   []string{"Supino, ginocchia piegate.", "Piedi a terra.", "Solleva il bacino verso l'alto.", "In alto contrai i glutei e scendi piano."},
		Correct: []string{"Spinta dai talloni.", "Bacino fino a una linea dritta.", "I glutei lavorano.", "La schiena non si iperestende."},
		Wrong:   []string{"Inarcare la schiena in alto.", "Piedi troppo vicini.", "Alzare i talloni.", "Sollevare il bacino di scatto."},
		Voice:   Voice{Start: "Ponte. Spingi dai talloni.", Mid: []string{"In alto contrai i glutei.", "Non inarcare la schiena."}, Finish: "Abbassa il bacino lentamente."},
	},
	"G02": {
		Desc:    "Ponte per i glutei con tenuta in alto.",
		HowTo:   []string{"Solleva il bacino verso l'alto.", "Tieni in alto.", "Contrai i glutei.", "Scendi lentamente."},
		Correct: []string{"Tenuta stabile.", "Glutei attivi.", "Le costole non sporgono.", "Discesa lenta."},
		Wrong:   []string{"Iperestendere la schiena.", "Perdere i piedi.", "Lasciar cadere il bacino.", "Trattenere il respiro."},
		Voice:   Voice{Start: "Ponte con tenuta. Su e tieni.", Mid: []string{"I glutei lavorano.", "Scendi lentamente."}, Finish: "Rilassa le gambe."},
	},
	"L01": {
		Desc:    "Squat poco profondo per gambe e glutei, con poco carico sul ginocchio.",
		HowTo:   []string{"Piedi un po' più larghi dei fianchi.", "Spingi il bacino all'indietro.", "Piega poco le ginocchia.", "Risali spingendo coi piedi."},
		Correct: []string{"Poca profondità.", "Ginocchia in direzione delle dita.", "Talloni a terra.", "Schiena piatta."},
		Wrong:   []string{"Scendere troppo.", "Lasciar cadere le ginocchia verso l'interno.", "Alzare i talloni.", "Lasciarsi cadere."},
		Safety:  "Se il ginocchio fa male, passa subito al ponte per i glutei.",
		Voice:   Voice{Start: "Mini squat. Poco profondo.", Mid: []string{"Bacino indietro.", "Ginocchia verso le dita."}, Finish: "Bene. Non scendere troppo."},
	},
	"A01": {
		Desc:    "Esercizio per i bicipiti senza attrezzi: un braccio oppone resistenza.",
		HowTo:   []string{"Piega al gomito il braccio che lavora.", "Con l'altra mano premi verso il basso sull'avambraccio.", "Il braccio che lavora sale lentamente.", "Mantieni la resistenza per tutto il percorso."},
		Correct: []string{"Movimento lento.", "Resistenza percepibile.", "Gomito vicino al corpo.", "La spalla non si alza."},
		Wrong:   []string{"Farlo senza resistenza.", "Tirare il braccio.", "Alzare la spalla.", "Trattenere il respiro."},
		Voice:   Voice{Start: "Bicipiti. Un braccio resiste all'altro.", Mid: []string{"Sali lentamente.", "Mantieni la resistenza."}, Finish: "Cambia braccio."},
	},
	"A02": {
		Desc:    "Tenuta statica per i bicipiti senza attrezzi.",
		HowTo:   []string{"Piega a circa 90° il braccio che lavora.", "Con l'altra mano premi verso il basso.", "Il braccio che lavora oppone resistenza.", "Mantieni la tensione senza muoverti."},
		Correct: []string{"Gomito a circa 90°.", "Tensione stabile.", "Spalle basse.", "Respirazione regolare."},
		Wrong:   []string{"Premere a scatti.", "Trattenere il respiro.", "Alzare la spalla.", "Torcere il tronco."},
		Voice:   Voice{Start: "Tenuta bicipiti. Premi uno contro l'altro.", Mid: []string{"Spalle basse.", "Respira, non bloccare."}, Last: "Cinque secondi.", Finish: "Cambia braccio."},
	},
	"S01": {
		Desc:    "Esercizio per le spalle, i deltoidi e la parte alta della schiena.",
		HowTo:   []string{"Apri le braccia all'altezza delle spalle.", "Fai piccoli cerchi.", "Tieni le spalle basse.", "Tieni il tronco dritto."},
		Correct: []string{"Ampiezza piccola.", "Braccia stabili.", "Collo rilassato.", "Respirazione regolare."},
		Wrong:   []string{"Grandi mulinelli.", "Tendere il collo.", "Alzare le spalle.", "Inarcare la schiena."},
		Voice:   Voice{Start: "Piccoli cerchi con le braccia.", Mid: []string{"Spalle basse.", "Cerchi piccoli."}, Last: "Cinque secondi.", Finish: "Abbassa le braccia."},
	},

	// ---- Defaticamento ----
	"CD01": {
		Desc:    "Abbassare il battito e rilassarsi dopo l'allenamento.",
		HowTo:   []string{"Sdraiati supino.", "Rilassa le spalle.", "Inspira con calma.", "Espira lentamente."},
		Correct: []string{"Respirazione calma.", "Spalle rilassate.", "L'addome si muove dolcemente.", "Nessuna tensione nel collo."},
		Wrong:   []string{"Trattenere il respiro.", "Contrarre il viso.", "Inarcare la schiena.", "Affrettarsi."},
		Voice:   Voice{Start: "Respira con calma.", Mid: []string{"Espira a lungo."}, Finish: "Passiamo agli allungamenti."},
	},
	"CD02": {
		Desc:    "Aprire dolcemente il petto e la parte anteriore della spalla.",
		HowTo:   []string{"Sdraiati supino.", "Apri le braccia ai lati.", "Rilassa le spalle.", "Respira con calma."},
		Correct: []string{"Il petto si apre dolcemente.", "Spalle senza tensione.", "Schiena tranquilla.", "Nessun dolore alla spalla."},
		Wrong:   []string{"Tirare le braccia fino al dolore.", "Inarcare la schiena.", "Alzare le spalle.", "Trattenere il respiro."},
		Voice:   Voice{Start: "Braccia ai lati. Petto aperto.", Mid: []string{"Non tirare fino al dolore."}, Finish: "Riporta le braccia lentamente."},
	},
	"CD03": {
		Desc:    "Allungamento dolce del tronco e della zona dorso-lombare.",
		HowTo:   []string{"Supino, ginocchia piegate.", "Abbassa dolcemente le ginocchia su un lato.", "Lascia le spalle sul tappetino.", "Ripeti dall'altro lato."},
		Correct: []string{"Movimento dolce.", "Le spalle non si sollevano.", "Nessun dolore alla schiena.", "Respirazione regolare."},
		Wrong:   []string{"Forzare le ginocchia a terra.", "Rotazione brusca.", "Sollevare una spalla.", "Sopportare il dolore."},
		Voice:   Voice{Start: "Ginocchia dolcemente su un lato.", Mid: []string{"Spalle a terra."}, Finish: "Torna dal centro."},
	},
	"CD04": {
		Desc:    "Allungamento dolce della parte posteriore della gamba dopo il carico.",
		HowTo:   []string{"Supino, solleva una gamba.", "Afferra la coscia o la tibia.", "Porta la gamba dolcemente verso di te.", "Ripeti con l'altra gamba."},
		Correct: []string{"Il ginocchio può restare un po' piegato.", "Schiena tranquilla.", "Allungamento dolce.", "Respirazione regolare."},
		Wrong:   []string{"Tirare la gamba con forza.", "Portare il piede al viso.", "Sollevare il bacino.", "Sopportare il dolore dietro al ginocchio."},
		Voice:   Voice{Start: "Solleva la gamba. Tira dolcemente.", Mid: []string{"Non fino al dolore."}, Finish: "Cambia lato con dolcezza."},
	},
	"CD05": {
		Desc:    "Allungamento della zona dei glutei e della parte posteriore del bacino.",
		HowTo:   []string{"Sdraiati supino.", "Appoggia un piede sull'altra coscia.", "Porta la coscia dolcemente verso di te.", "Non premere sul ginocchio."},
		Correct: []string{"Sensazione nel gluteo.", "Il ginocchio non fa male.", "Schiena tranquilla.", "Movimento dolce."},
		Wrong:   []string{"Premere il ginocchio con la mano.", "Forzare fino al dolore.", "Torcere il bacino.", "Trattenere il respiro."},
		Safety:  "Se il ginocchio disturba, fai un allungamento dolce dei glutei da sdraiato.",
		Voice:   Voice{Start: "Figura quattro. Non premere sul ginocchio.", Mid: []string{"Porta dolcemente verso di te."}, Finish: "Cambia lato con dolcezza."},
	},
	"CD06": {
		Desc:    "Aprire dolcemente la parte anteriore del corpo e la colonna dorsale.",
		HowTo:   []string{"Sdraiati prono.", "Appoggia gli avambracci a terra.", "Solleva dolcemente il petto.", "Tieni il collo lungo."},
		Correct: []string{"Sollevamento dolce.", "Gomiti sotto le spalle o un po' avanti.", "Spalle senza tensione.", "Schiena senza dolore."},
		Wrong:   []string{"Inclinare la testa indietro.", "Inarcarsi troppo.", "Contrarre le spalle.", "Sopportare il dolore alla schiena."},
		Voice:   Voice{Start: "Posizione della sfinge. Sollevamento dolce.", Mid: []string{"Collo lungo."}, Finish: "Scendi sul tappetino."},
	},
}
