package content

// detailsEN is the English rich content + voice for every exercise.
var detailsEN = map[string]Detail{
	// ---- Warm-up ----
	"W01": {
		Desc:    "A gentle start: breathing, spinal lengthening and posture.",
		HowTo:   []string{"Stand tall, feet hip-width apart.", "On the inhale, reach gently up through the crown.", "You can raise the arms out to the sides.", "On the exhale, drop the shoulders and relax the neck."},
		Correct: []string{"Feet steady on the floor.", "Shoulders don't rise to the ears.", "Long neck.", "Calm breathing."},
		Wrong:   []string{"Tipping the head back.", "Over-arching the lower back.", "Raising the shoulders.", "Holding the breath."},
		Voice:   Voice{Start: "Stand tall. Breathe calmly.", Mid: []string{"Reach up through the crown."}, Finish: "Shoulders down. Next."},
	},
	"W02": {
		Desc:    "Mobilizing the neck before the workout.",
		HowTo:   []string{"Stand straight.", "Slowly turn the head right.", "Return to center.", "Turn the head left."},
		Correct: []string{"Slow movement.", "Shoulders stay down.", "Torso doesn't turn.", "Comfortable range."},
		Wrong:   []string{"Jerky moves.", "Tipping the head back.", "Raising the shoulders.", "Stretching the neck through pain."},
		Voice:   Voice{Start: "Turning the head.", Mid: []string{"Gently, no jerks."}, Finish: "Head to center."},
	},
	"W03": {
		Desc:    "Warming the shoulder joints and upper back.",
		HowTo:   []string{"Stand straight.", "Lift the shoulders slightly.", "Take them back.", "Lower and repeat the circle."},
		Correct: []string{"Smooth shoulders.", "Relaxed arms.", "Neck stays free.", "Stable torso."},
		Wrong:   []string{"Jerking the shoulders.", "Slouching.", "Tensing the neck.", "Too large a range."},
		Voice:   Voice{Start: "Shoulder circles back.", Mid: []string{"Free neck."}, Finish: "Drop the shoulders."},
	},
	"W04": {
		Desc:    "More shoulder and upper-back mobility.",
		HowTo:   []string{"Stand straight.", "Circle the shoulders forward.", "Keep the neck free.", "Don't sway the torso."},
		Correct: []string{"Controlled movement.", "Shoulders not tense.", "Even breathing.", "Torso doesn't sway."},
		Wrong:   []string{"Shoulders to the ears.", "Moving sharply.", "Rounding the back.", "Holding the breath."},
		Voice:   Voice{Start: "Circles forward.", Mid: []string{"Don't tense the neck."}, Finish: "Relax the shoulders."},
	},
	"W05": {
		Desc:    "Warming the shoulders, delts and upper back.",
		HowTo:   []string{"Arms out to the sides at shoulder height.", "Make small circles forward.", "Keep the shoulders down.", "Don't hold the breath."},
		Correct: []string{"Small circles.", "Arms at shoulder height.", "Relaxed neck.", "Torso doesn't sway."},
		Wrong:   []string{"Big swings.", "Shoulders to the ears.", "Arching the lower back.", "Tensing the neck."},
		Voice:   Voice{Start: "Arms out. Small circles.", Mid: []string{"Shoulders down."}, Finish: "Lower the arms."},
	},
	"W06": {
		Desc:    "Warming the shoulders and scapular stabilizers.",
		HowTo:   []string{"Arms out to the sides.", "Make small circles backward.", "Don't raise the shoulders.", "Keep the torso steady."},
		Correct: []string{"Short movement.", "Shoulders down.", "Blades work gently.", "Calm breathing."},
		Wrong:   []string{"Jerking.", "Wide swings.", "Slouching.", "Tensing the neck."},
		Voice:   Voice{Start: "Circles back.", Mid: []string{"Small range."}, Finish: "Relax the arms."},
	},
	"W07": {
		Desc:    "Engages the upper back and opens the chest.",
		HowTo:   []string{"Stand straight.", "Take the arms slightly back.", "Gently squeeze the shoulder blades.", "Return to neutral."},
		Correct: []string{"Chest opens.", "Shoulders stay down.", "Blades work gently.", "Lower back doesn't arch."},
		Wrong:   []string{"Cranking the lower back.", "Lifting the chin.", "Jerking the arms.", "Raising the shoulders."},
		Voice:   Voice{Start: "Open the chest.", Mid: []string{"Blades gently back."}, Finish: "Back to center."},
	},
	"W08": {
		Desc:    "Gentle mobility for the mid-back and torso.",
		HowTo:   []string{"Stand straight.", "Turn the torso right.", "Return to center.", "Turn the torso left."},
		Correct: []string{"Movement comes from the torso.", "Hips nearly still.", "Feet don't twist.", "Comfortable range."},
		Wrong:   []string{"Twisting sharply.", "Twisting the knees.", "Jerking the feet.", "Leaning back."},
		Voice:   Voice{Start: "Torso twists.", Mid: []string{"Feet steady."}, Finish: "Back to center."},
	},
	"W09": {
		Desc:    "Warms the hips and hamstrings; teaches bending without rounding the back.",
		HowTo:   []string{"Stand straight, soften the knees slightly.", "Send the hips back.", "Hinge the torso with a straight back.", "Return up."},
		Correct: []string{"Flat back.", "Movement starts from the hips.", "Knees slightly soft.", "Neck continues the spine line."},
		Wrong:   []string{"Rounding the back.", "Turning it into a squat.", "Reaching down through force.", "Lifting the head."},
		Voice:   Voice{Start: "Hips back, flat back.", Mid: []string{"Don't round the back."}, Finish: "Rise up calmly."},
	},
	"W10": {
		Desc:    "Warming the feet, calves and balance.",
		HowTo:   []string{"Stand straight.", "Rise onto the toes.", "Hold for a moment.", "Lower slowly."},
		Correct: []string{"Body vertical.", "Smooth movement.", "Steady feet.", "Knees don't cave in."},
		Wrong:   []string{"Dropping the heels.", "Swaying.", "Rolling onto the outer foot.", "Jerking."},
		Voice:   Voice{Start: "Rise onto the toes.", Mid: []string{"Slowly down."}, Finish: "Steady feet."},
	},

	// ---- Main ----
	"M01": {
		Desc:      "A base exercise for chest, triceps, shoulders and core.",
		HowTo:     []string{"Hands under or slightly wider than the shoulders.", "Legs extended, body straight.", "Lower smoothly.", "Press up without a jerk."},
		Correct:   []string{"Straight body.", "Belly tight.", "Elbows not flared straight out.", "Controlled movement."},
		Wrong:     []string{"Sagging lower back.", "Hips up.", "Dropping down.", "Elbows flared to 90°."},
		Breathing: "Inhale down, exhale up.",
		Voice:     Voice{Start: "Body straight. Begin.", Mid: []string{"Belly tight.", "Elbows not too wide."}, Finish: "Done. Relax the shoulders."},
	},
	"M02": {
		Desc:      "A push-up variation with more triceps emphasis.",
		HowTo:     []string{"Hands roughly under the shoulders.", "Point the elbows back, close to the body.", "Lower slowly.", "Press up without a jerk."},
		Correct:   []string{"Straight body.", "Elbows don't flare wide.", "Shoulders not tense.", "Wrists pain-free."},
		Wrong:     []string{"Hands too close together.", "Bending the wrists.", "Flaring the elbows.", "Losing the body line."},
		Breathing: "Inhale down, exhale up.",
		Safety:    "If elbows or wrists hurt, switch to regular push-ups with fewer reps.",
		Voice:     Voice{Start: "Narrow push-ups. Elbows close.", Mid: []string{"No pressure on the wrists.", "Keep the body straight."}, Finish: "Good. Relax the shoulders."},
	},
	"M03": {
		Desc:      "Push-ups with control at the bottom.",
		HowTo:     []string{"Get into the push-up position.", "Lower slowly.", "Hold 1 second.", "Press up."},
		Correct:   []string{"Controlled pause.", "Body doesn't sag.", "Elbows under control.", "No dropping."},
		Wrong:     []string{"Dropping down.", "Relaxing at the bottom.", "Holding the breath.", "Arching the lower back."},
		Breathing: "Inhale down, short pause, exhale up.",
		Voice:     Voice{Start: "Slowly down. Pause at the bottom.", Mid: []string{"Don't drop, control it.", "Lower back doesn't sag."}, Finish: "Great. Rest."},
	},
	"C01": {
		Desc:    "An exercise for the abs and pelvic control.",
		HowTo:   []string{"Lie on your back.", "Press the lower back to the mat.", "Lift the legs.", "Cross the legs with a short range."},
		Correct: []string{"Lower back on the mat.", "Legs not too low.", "Relaxed neck.", "Controlled movement."},
		Wrong:   []string{"Lifting the lower back.", "Dropping the legs too low.", "Pulling the neck forward.", "Jerky swings."},
		Safety:  "If the lower back lifts, switch to Toe taps or Dead bug.",
		Voice:   Voice{Start: "Scissors. Lower back pressed.", Mid: []string{"Legs higher if it pulls the back.", "Relaxed neck."}, Last: "Five seconds.", Finish: "Lower the legs gently."},
	},
	"C02": {
		Desc:      "A static exercise for abs, shoulders, glutes and core stability.",
		HowTo:     []string{"Get onto your elbows and toes.", "Elbows under the shoulders.", "Tighten the belly and glutes.", "Hold a straight body line."},
		Correct:   []string{"Shoulders over elbows.", "Hips don't sag.", "Belly tight.", "Gaze down."},
		Wrong:     []string{"Sagging lower back.", "Hips up like a tent.", "Looking forward.", "Holding the breath."},
		Breathing: "Short inhale, long calm exhale.",
		Voice:     Voice{Start: "Plank. Body in one line.", Mid: []string{"Belly tight.", "Don't let the back sag."}, Last: "Five seconds.", Finish: "Lower the knees."},
	},
	"C03": {
		Desc:    "An exercise for the abs and lower-back control.",
		HowTo:   []string{"Lie on your back.", "Press the lower back to the mat.", "Lift the legs.", "Short alternating up-and-down moves."},
		Correct: []string{"Stable lower back.", "Short range.", "Legs not too low.", "Even breathing."},
		Wrong:   []string{"Arching the lower back.", "Big swings.", "Tensing the neck.", "Holding the breath."},
		Safety:  "If the lower back lifts, raise the legs higher or switch to Dead bug.",
		Voice:   Voice{Start: "Lower back pressed.", Mid: []string{"Short range.", "Breathe evenly."}, Last: "Five seconds.", Finish: "Lower the legs slowly."},
	},
	"C04": {
		Desc:      "A safe exercise for the deep core and stability.",
		HowTo:     []string{"Lie on your back, arms up.", "Knees bent at 90°.", "Slowly lower the opposite arm and leg.", "Return and repeat on the other side."},
		Correct:   []string{"Lower back pressed.", "Slow movement.", "Torso doesn't sway.", "Range under control."},
		Wrong:     []string{"Lifting the lower back.", "Moving fast.", "Lowering the leg too far.", "Losing pelvic control."},
		Breathing: "Exhale as the arm and leg extend.",
		Voice:     Voice{Start: "Dead bug. Lower back pressed.", Mid: []string{"Move slowly.", "Torso doesn't sway."}, Finish: "Good. Bring the legs back."},
	},
	"C05": {
		Desc:    "An exercise for the obliques and lateral stability.",
		HowTo:   []string{"Lie on your side.", "Place the elbow under the shoulder.", "Lift the hips.", "Hold the body in one line."},
		Correct: []string{"Elbow under the shoulder.", "Hips lifted.", "Body doesn't tip.", "Neutral neck."},
		Wrong:   []string{"Sagging hips.", "Shoulder pinched to the ear.", "Rolling the torso down.", "Holding the breath."},
		Safety:  "If the shoulder hurts, cut the time by 50% or use a regular plank.",
		Voice:   Voice{Start: "Side plank. Elbow under the shoulder.", Mid: []string{"Keep the hips up.", "Free neck."}, Last: "Five seconds.", Finish: "Lower down gently."},
	},
	"C06": {
		Desc:    "A control exercise for the abs; a gentler alternative to scissors.",
		HowTo:   []string{"Lie on your back, legs at 90°.", "Slowly lower one heel to the floor.", "Bring the leg back.", "Repeat with the other leg."},
		Correct: []string{"Lower back doesn't lift.", "Slow movement.", "Stable pelvis.", "Heel touches gently."},
		Wrong:   []string{"Dropping the leg down.", "Arching the lower back.", "Moving both legs at once.", "Rushing."},
		Voice:   Voice{Start: "Toe taps. Slowly.", Mid: []string{"Lower back on the mat.", "Gentle touch."}, Finish: "Relax the belly."},
	},
	"C07": {
		Desc:    "A static exercise for the abs and core control.",
		HowTo:   []string{"Lie on your back, lower back pressed.", "Lift the shoulders slightly.", "Knees bent or slightly raised.", "Hold the position."},
		Correct: []string{"Lower back on the floor.", "Belly tight.", "Neck doesn't strain forward.", "Breathing isn't held."},
		Wrong:   []string{"Arching the lower back.", "Lifting the chin.", "Legs too low.", "Pushing through back pain."},
		Safety:  "If it pulls the lower back, bend the knees or switch to Dead bug.",
		Voice:   Voice{Start: "Hollow hold. Lower back pressed.", Mid: []string{"Breathe evenly.", "If it pulls the back, bend the knees."}, Last: "Five seconds.", Finish: "Lower the shoulders and legs."},
	},
	"C08": {
		Desc:      "A short, hard plank with maximum full-body tension.",
		HowTo:     []string{"Get into a forearm plank.", "Elbows under the shoulders.", "Brace the abs and glutes.", "Pull the elbows toward the toes."},
		Correct:   []string{"Strong belly brace.", "Glutes engaged.", "Straight body.", "Breathing without holding."},
		Wrong:     []string{"Holding it like a relaxed plank.", "Sagging lower back.", "Holding the breath.", "Staying too long."},
		Breathing: "Short breaths, no holding.",
		Safety:    "Too hard — switch to a regular plank for 45–60 seconds.",
		Voice:     Voice{Start: "Brace abs and glutes.", Mid: []string{"Elbows toward the toes.", "Whole body tight."}, Last: "Five seconds.", Finish: "Lower the knees."},
	},
	"B01": {
		Desc:    "An exercise for the back, glutes and posterior chain.",
		HowTo:   []string{"Lie face down.", "Extend the arms forward or alongside the body.", "Lift the chest and legs slightly.", "Lower with control."},
		Correct: []string{"Small lift.", "Neck continues the spine line.", "Glutes lightly engaged.", "No jerking."},
		Wrong:   []string{"Cranking the lower back.", "Lifting the head.", "Raising the legs too high.", "Jerking."},
		Voice:   Voice{Start: "Boat. Small lift.", Mid: []string{"Neutral neck.", "Don't crank the back."}, Finish: "Lower gently."},
	},
	"B02": {
		Desc:    "An exercise for the upper back, shoulder blades and rear delts.",
		HowTo:   []string{"Lie face down.", "Lift the chest slightly or keep it on the floor.", "Sweep the arms in an arc to overhead.", "Bring the arms back."},
		Correct: []string{"Relaxed neck.", "Blades working.", "Comfortable range.", "Lower back not overloaded."},
		Wrong:   []string{"Lifting the head.", "Arching too much.", "Jerking the arms.", "Shoulders to the ears."},
		Voice:   Voice{Start: "Arms in an arc. Head down.", Mid: []string{"Blades working.", "Don't tense the neck."}, Finish: "Relax the arms."},
	},
	"B03": {
		Desc:    "A static hold for the back and glutes.",
		HowTo:   []string{"Lie face down.", "Lift the chest and legs slightly.", "Hold the position.", "Breathe evenly."},
		Correct: []string{"Moderate lift.", "Neutral neck.", "Glutes engaged.", "Even breathing."},
		Wrong:   []string{"Lifting the head.", "Arching too hard.", "Holding the breath.", "Pushing through back pain."},
		Safety:  "Lower-back discomfort — a boat with a smaller range.",
		Voice:   Voice{Start: "Hold the boat.", Mid: []string{"Breathe evenly.", "Long neck."}, Last: "Five seconds.", Finish: "Lower gently."},
	},
	"B04": {
		Desc:    "An exercise for the upper back, shoulder blades and rear delts.",
		HowTo:   []string{"Lie face down.", "Bend the arms into a 'W'.", "Lift the elbows and hands slightly.", "Squeeze the blades and lower."},
		Correct: []string{"Small movement.", "Blades working.", "Head looking down.", "Shoulders not to the ears."},
		Wrong:   []string{"Lifting the head.", "Raising the arms too high.", "Tensing the neck.", "Arching the lower back."},
		Voice:   Voice{Start: "W-raise. Blades back.", Mid: []string{"Head down.", "Small movement."}, Finish: "Lower the arms."},
	},
	"B05": {
		Desc:    "An exercise for the upper back, shoulders and lower traps.",
		HowTo:   []string{"Lie face down.", "Extend the arms diagonally into a 'Y'.", "Lift the arms slightly off the floor.", "Lower them back."},
		Correct: []string{"Arms lift only a little.", "Blades down and back.", "Neutral neck.", "Calm lower back."},
		Wrong:   []string{"Jerky swing.", "Lifting the head.", "Shoulders to the ears.", "Arching hard."},
		Voice:   Voice{Start: "Y-raise. Diagonal arms.", Mid: []string{"Shoulders not to the ears.", "Small lift."}, Finish: "Relax the back."},
	},
	"G01": {
		Desc:    "An exercise for the glutes, hamstrings and pelvic stability.",
		HowTo:   []string{"Lie on your back, knees bent.", "Feet on the floor.", "Lift the hips up.", "Squeeze the glutes at the top, lower slowly."},
		Correct: []string{"Push through the heels.", "Hips to a straight line.", "Glutes working.", "Lower back doesn't over-extend."},
		Wrong:   []string{"Arching the lower back at the top.", "Feet too close.", "Lifting the heels.", "Jerking the hips up."},
		Voice:   Voice{Start: "Bridge. Push through the heels.", Mid: []string{"Squeeze the glutes at the top.", "Don't arch the back."}, Finish: "Lower the hips slowly."},
	},
	"G02": {
		Desc:    "A glute bridge with a hold at the top.",
		HowTo:   []string{"Lift the hips up.", "Hold at the top.", "Squeeze the glutes.", "Lower slowly."},
		Correct: []string{"Stable hold.", "Glutes engaged.", "Ribs not flaring.", "Slow descent."},
		Wrong:   []string{"Over-extending the lower back.", "Losing the feet.", "Dropping the hips.", "Holding the breath."},
		Voice:   Voice{Start: "Bridge with a hold. Up and hold.", Mid: []string{"Glutes working.", "Lower slowly."}, Finish: "Relax the legs."},
	},
	"L01": {
		Desc:    "A shallow squat for legs and glutes with limited knee load.",
		HowTo:   []string{"Feet a bit wider than the hips.", "Send the hips back.", "Bend the knees shallowly.", "Return up through the feet."},
		Correct: []string{"Small depth.", "Knees track the toes.", "Heels on the floor.", "Flat back."},
		Wrong:   []string{"Going deep.", "Knees caving in.", "Lifting the heels.", "Dropping down."},
		Safety:  "If the knee hurts, switch to the glute bridge right away.",
		Voice:   Voice{Start: "Mini squat. Shallow.", Mid: []string{"Hips back.", "Knees track the toes."}, Finish: "Good. No depth."},
	},
	"A01": {
		Desc:    "A bicep exercise without equipment: one arm resists the other.",
		HowTo:   []string{"Bend the working arm at the elbow.", "Press down on the forearm with the other hand.", "The working arm rises slowly.", "Keep resistance the whole way."},
		Correct: []string{"Slow movement.", "Noticeable resistance.", "Elbow close to the body.", "Shoulder doesn't rise."},
		Wrong:   []string{"Doing it without resistance.", "Jerking the arm.", "Raising the shoulder.", "Holding the breath."},
		Voice:   Voice{Start: "Biceps. One arm resists the other.", Mid: []string{"Slowly up.", "Keep the resistance."}, Finish: "Switch arms."},
	},
	"A02": {
		Desc:    "A static bicep hold without equipment.",
		HowTo:   []string{"Bend the working arm to about 90°.", "Press down with the other hand.", "The working arm resists.", "Hold the tension without moving."},
		Correct: []string{"Elbow about 90°.", "Steady tension.", "Shoulders down.", "Even breathing."},
		Wrong:   []string{"Pressing in jerks.", "Holding the breath.", "Raising the shoulder.", "Twisting the torso."},
		Voice:   Voice{Start: "Bicep hold. Press against each other.", Mid: []string{"Shoulders down.", "Breathe, don't hold."}, Last: "Five seconds.", Finish: "Switch arms."},
	},
	"S01": {
		Desc:    "An exercise for the shoulders, delts and upper back.",
		HowTo:   []string{"Arms out at shoulder height.", "Make small circles.", "Keep the shoulders down.", "Keep the torso straight."},
		Correct: []string{"Small range.", "Steady arms.", "Relaxed neck.", "Even breathing."},
		Wrong:   []string{"Big swings.", "Tensing the neck.", "Raising the shoulders.", "Arching the lower back."},
		Voice:   Voice{Start: "Small arm circles.", Mid: []string{"Shoulders down.", "Small circles."}, Last: "Five seconds.", Finish: "Lower the arms."},
	},

	// ---- Cool-down ----
	"CD01": {
		Desc:    "Lowering the heart rate and relaxing after the workout.",
		HowTo:   []string{"Lie on your back.", "Relax the shoulders.", "Take a calm inhale.", "Exhale slowly."},
		Correct: []string{"Calm breathing.", "Relaxed shoulders.", "Belly moves gently.", "No neck tension."},
		Wrong:   []string{"Holding the breath.", "Tensing the face.", "Arching the lower back.", "Rushing."},
		Voice:   Voice{Start: "Breathe calmly.", Mid: []string{"Long exhale."}, Finish: "On to the stretch."},
	},
	"CD02": {
		Desc:    "A gentle opening of the chest and front of the shoulders.",
		HowTo:   []string{"Lie on your back.", "Spread the arms out to the sides.", "Relax the shoulders.", "Breathe calmly."},
		Correct: []string{"Chest opens gently.", "Shoulders not pinched.", "Calm lower back.", "No shoulder pain."},
		Wrong:   []string{"Pulling the arms through pain.", "Arching the lower back.", "Raising the shoulders.", "Holding the breath."},
		Voice:   Voice{Start: "Arms out. Open the chest.", Mid: []string{"Don't pull through pain."}, Finish: "Slowly bring the arms back."},
	},
	"CD03": {
		Desc:    "A gentle stretch of the torso and thoraco-lumbar area.",
		HowTo:   []string{"Lie on your back, knees bent.", "Gently lower the knees to one side.", "Keep the shoulders on the mat.", "Repeat on the other side."},
		Correct: []string{"Gentle movement.", "Shoulders don't lift.", "No lower-back pain.", "Even breathing."},
		Wrong:   []string{"Forcing the knees down.", "A sharp twist.", "Lifting a shoulder.", "Pushing through pain."},
		Voice:   Voice{Start: "Knees gently to the side.", Mid: []string{"Shoulders on the floor."}, Finish: "Return through center."},
	},
	"CD04": {
		Desc:    "A gentle hamstring stretch after the load.",
		HowTo:   []string{"Lie on your back, lift one leg.", "Hold the thigh or shin.", "Gently draw the leg toward you.", "Repeat with the other leg."},
		Correct: []string{"The knee can bend slightly.", "Calm lower back.", "Gentle stretch.", "Even breathing."},
		Wrong:   []string{"Pulling the leg by force.", "Reaching the foot to the face.", "Lifting the hips.", "Pushing through pain behind the knee."},
		Voice:   Voice{Start: "Lift the leg. Stretch gently.", Mid: []string{"Not through pain."}, Finish: "Switch sides smoothly."},
	},
	"CD05": {
		Desc:    "A stretch for the glutes and the back of the pelvis.",
		HowTo:   []string{"Lie on your back.", "Place one foot on the other thigh.", "Gently draw the thigh toward you.", "Don't press on the knee."},
		Correct: []string{"Feeling in the glute.", "Knee doesn't hurt.", "Calm lower back.", "Gentle movement."},
		Wrong:   []string{"Pressing on the knee with the hand.", "Pulling through pain.", "Twisting the pelvis.", "Holding the breath."},
		Safety:  "Knee discomfort — a gentle lying glute stretch instead.",
		Voice:   Voice{Start: "Figure four. No pressure on the knee.", Mid: []string{"Draw it gently toward you."}, Finish: "Switch sides smoothly."},
	},
	"CD06": {
		Desc:    "A gentle opening of the front of the body and the mid-back.",
		HowTo:   []string{"Lie face down.", "Place the forearms on the floor.", "Gently lift the chest.", "Keep the neck long."},
		Correct: []string{"Gentle lift.", "Elbows under or just ahead of the shoulders.", "Shoulders not pinched.", "Lower back pain-free."},
		Wrong:   []string{"Tipping the head back.", "Arching too much.", "Pinching the shoulders.", "Pushing through back pain."},
		Voice:   Voice{Start: "Sphinx pose. Gentle lift.", Mid: []string{"Long neck."}, Finish: "Lower down to the mat."},
	},
}
