package content

// detailsFR is the French rich content + voice for every exercise.
var detailsFR = map[string]Detail{
	// ---- Échauffement ----
	"W01": {
		Desc:    "Un début en douceur : respiration, allongement de la colonne et posture.",
		HowTo:   []string{"Tiens-toi droit, pieds écartés de la largeur des hanches.", "À l'inspiration, étire-toi doucement vers le haut par le sommet du crâne.", "Tu peux lever les bras sur les côtés.", "À l'expiration, abaisse les épaules et relâche la nuque."},
		Correct: []string{"Pieds bien ancrés au sol.", "Les épaules ne montent pas aux oreilles.", "Nuque longue.", "Respiration calme."},
		Wrong:   []string{"Basculer la tête en arrière.", "Trop cambrer le bas du dos.", "Lever les épaules.", "Retenir sa respiration."},
		Voice:   Voice{Start: "Tiens-toi droit. Respire calmement.", Mid: []string{"Étire-toi par le sommet du crâne."}, Finish: "Épaules basses. Continue."},
	},
	"W02": {
		Desc:    "Mobiliser la nuque avant l'entraînement.",
		HowTo:   []string{"Tiens-toi droit.", "Tourne lentement la tête à droite.", "Reviens au centre.", "Tourne la tête à gauche."},
		Correct: []string{"Mouvement lent.", "Les épaules restent basses.", "Le tronc ne tourne pas.", "Amplitude confortable."},
		Wrong:   []string{"Mouvements brusques.", "Basculer la tête en arrière.", "Lever les épaules.", "Étirer la nuque jusqu'à la douleur."},
		Voice:   Voice{Start: "On tourne la tête.", Mid: []string{"En douceur, sans à-coup."}, Finish: "Tête au centre."},
	},
	"W03": {
		Desc:    "Échauffer les articulations des épaules et le haut du dos.",
		HowTo:   []string{"Tiens-toi droit.", "Monte un peu les épaules.", "Amène-les en arrière.", "Abaisse et répète le cercle."},
		Correct: []string{"Les épaules bougent en souplesse.", "Bras détendus.", "La nuque reste libre.", "Tronc stable."},
		Wrong:   []string{"Secouer les épaules.", "Se voûter.", "Tendre la nuque.", "Amplitude trop large."},
		Voice:   Voice{Start: "Cercles d'épaules, en arrière.", Mid: []string{"Nuque libre."}, Finish: "Abaisse les épaules."},
	},
	"W04": {
		Desc:    "Plus de mobilité pour les épaules et le haut du dos.",
		HowTo:   []string{"Tiens-toi droit.", "Tourne les épaules vers l'avant.", "Garde la nuque libre.", "Ne balance pas le tronc."},
		Correct: []string{"Mouvement contrôlé.", "Épaules sans tension.", "Respiration régulière.", "Le tronc ne se balance pas."},
		Wrong:   []string{"Épaules aux oreilles.", "Mouvement brusque.", "Arrondir le dos.", "Retenir sa respiration."},
		Voice:   Voice{Start: "Cercles vers l'avant.", Mid: []string{"Ne tends pas la nuque."}, Finish: "Relâche les épaules."},
	},
	"W05": {
		Desc:    "Échauffer les épaules, les deltoïdes et le haut du dos.",
		HowTo:   []string{"Bras sur les côtés, à hauteur d'épaules.", "Petits cercles vers l'avant.", "Garde les épaules basses.", "Ne retiens pas ta respiration."},
		Correct: []string{"Petits cercles.", "Bras à hauteur d'épaules.", "Nuque détendue.", "Le tronc ne se balance pas."},
		Wrong:   []string{"Grands moulinets.", "Épaules aux oreilles.", "Cambrer le dos.", "Tendre la nuque."},
		Voice:   Voice{Start: "Bras sur les côtés. Petits cercles.", Mid: []string{"Épaules basses."}, Finish: "Abaisse les bras."},
	},
	"W06": {
		Desc:    "Échauffer les épaules et les stabilisateurs de l'omoplate.",
		HowTo:   []string{"Bras sur les côtés.", "Petits cercles vers l'arrière.", "Ne lève pas les épaules.", "Garde le tronc droit."},
		Correct: []string{"Mouvement court.", "Épaules basses.", "Les omoplates travaillent en douceur.", "Respiration calme."},
		Wrong:   []string{"À-coups.", "Larges moulinets.", "Se voûter.", "Tendre la nuque."},
		Voice:   Voice{Start: "Cercles vers l'arrière.", Mid: []string{"Petite amplitude."}, Finish: "Relâche les bras."},
	},
	"W07": {
		Desc:    "Active le haut du dos et ouvre la poitrine.",
		HowTo:   []string{"Tiens-toi droit.", "Amène les bras un peu en arrière.", "Rapproche doucement les omoplates.", "Reviens en position neutre."},
		Correct: []string{"La poitrine s'ouvre.", "Épaules basses.", "Les omoplates travaillent en douceur.", "Le dos ne se cambre pas."},
		Wrong:   []string{"Casser le dos en arrière.", "Lever le menton.", "Tirer sur les bras.", "Lever les épaules."},
		Voice:   Voice{Start: "On ouvre la poitrine.", Mid: []string{"Omoplates doucement en arrière."}, Finish: "Reviens au centre."},
	},
	"W08": {
		Desc:    "Mobilité douce pour la colonne dorsale et le tronc.",
		HowTo:   []string{"Tiens-toi droit.", "Tourne le tronc à droite.", "Reviens au centre.", "Tourne le tronc à gauche."},
		Correct: []string{"Le mouvement vient du tronc.", "Bassin presque immobile.", "Les pieds ne tournent pas.", "Amplitude confortable."},
		Wrong:   []string{"Tourner le tronc brusquement.", "Tordre les genoux.", "Secouer les pieds.", "Tomber en arrière."},
		Voice:   Voice{Start: "Rotations du tronc.", Mid: []string{"Pieds ancrés."}, Finish: "Reviens au centre."},
	},
	"W09": {
		Desc:    "Échauffe la hanche et l'arrière de la jambe ; apprend à se pencher sans arrondir le dos.",
		HowTo:   []string{"Tiens-toi droit, genoux légèrement souples.", "Pousse le bassin vers l'arrière.", "Penche le tronc dos plat.", "Redresse-toi."},
		Correct: []string{"Dos plat.", "Le mouvement part de la hanche.", "Genoux légèrement souples.", "La nuque suit la ligne du dos."},
		Wrong:   []string{"Arrondir le dos.", "Le transformer en squat.", "Forcer pour atteindre le sol.", "Lever la tête."},
		Voice:   Voice{Start: "Bassin en arrière, dos plat.", Mid: []string{"N'arrondis pas le dos."}, Finish: "Redresse-toi calmement."},
	},
	"W10": {
		Desc:    "Échauffer les pieds, les mollets et l'équilibre.",
		HowTo:   []string{"Tiens-toi droit.", "Monte sur la pointe des pieds.", "Tiens un instant.", "Redescends lentement."},
		Correct: []string{"Corps vertical.", "Mouvement fluide.", "Pieds stables.", "Les genoux ne rentrent pas."},
		Wrong:   []string{"Laisser tomber les talons.", "Se balancer.", "Tomber sur le bord externe du pied.", "Faire des à-coups."},
		Voice:   Voice{Start: "Monte sur la pointe.", Mid: []string{"Redescends lentement."}, Finish: "Pieds stables."},
	},

	// ---- Bloc principal ----
	"M01": {
		Desc:      "Exercice de base pour la poitrine, les triceps, les épaules et le tronc.",
		HowTo:     []string{"Mains sous les épaules ou un peu plus larges.", "Jambes tendues, corps droit.", "Descends lentement.", "Pousse vers le haut sans à-coup."},
		Correct:   []string{"Corps droit.", "Ventre gainé.", "Les coudes ne s'écartent pas complètement.", "Mouvement contrôlé."},
		Wrong:     []string{"Creuser le bas du dos.", "Lever le bassin.", "Se laisser tomber.", "Écarter les coudes à 90°."},
		Breathing: "Inspire en descendant, expire en remontant.",
		Voice:     Voice{Start: "Corps droit. On commence.", Mid: []string{"Ventre gainé.", "Coudes pas trop écartés."}, Finish: "Terminé. Relâche les épaules."},
	},
	"M02": {
		Desc:      "Une variante de pompe plus axée sur les triceps.",
		HowTo:     []string{"Mains à peu près sous les épaules.", "Coudes vers l'arrière, près du corps.", "Descends lentement.", "Pousse sans à-coup."},
		Correct:   []string{"Corps droit.", "Les coudes ne s'écartent pas.", "Épaules sans tension.", "Poignets sans douleur."},
		Wrong:     []string{"Mains trop rapprochées.", "Plier les poignets.", "Écarter les coudes.", "Perdre la ligne du corps."},
		Breathing: "Inspire en descendant, expire en remontant.",
		Safety:    "Si les coudes ou les poignets font mal, passe à la pompe normale avec moins de répétitions.",
		Voice:     Voice{Start: "Pompe serrée. Coudes près du corps.", Mid: []string{"N'appuie pas sur les poignets.", "Corps droit."}, Finish: "Bien. Relâche les épaules."},
	},
	"M03": {
		Desc:      "Pompe avec contrôle au point le plus bas.",
		HowTo:     []string{"Mets-toi en position de pompe.", "Descends lentement.", "Tiens 1 seconde.", "Pousse vers le haut."},
		Correct:   []string{"Pause contrôlée.", "Le corps ne s'affaisse pas.", "Coudes sous contrôle.", "Aucune chute."},
		Wrong:     []string{"Se laisser tomber.", "Se relâcher en bas.", "Retenir sa respiration.", "Cambrer le bas du dos."},
		Breathing: "Inspire, courte pause, expire en remontant.",
		Voice:     Voice{Start: "Descends lentement. Tiens en bas.", Mid: []string{"Ne tombe pas, contrôle.", "Le bas du dos ne s'affaisse pas."}, Finish: "Super. Repose-toi."},
	},
	"C01": {
		Desc:    "Exercice pour les abdominaux et le contrôle du bassin.",
		HowTo:   []string{"Allonge-toi sur le dos.", "Plaque le bas du dos contre le tapis.", "Lève les jambes.", "Croise sur une faible amplitude."},
		Correct: []string{"Dos sur le tapis.", "Jambes pas trop basses.", "Nuque détendue.", "Mouvement contrôlé."},
		Wrong:   []string{"Décoller le dos.", "Trop descendre les jambes.", "Tirer la nuque vers l'avant.", "Moulinets brusques."},
		Safety:  "Si le dos se décolle, passe aux Toe taps ou au Dead bug.",
		Voice:   Voice{Start: "Ciseaux. Dos plaqué.", Mid: []string{"Monte les jambes si le dos tire.", "Nuque détendue."}, Last: "Cinq secondes.", Finish: "Repose les jambes doucement."},
	},
	"C02": {
		Desc:      "Exercice statique pour les abdominaux, les épaules, les fessiers et la stabilité du tronc.",
		HowTo:     []string{"Appuie-toi sur les coudes et la pointe des pieds.", "Coudes sous les épaules.", "Gaine le ventre et les fessiers.", "Garde une ligne de corps droite."},
		Correct:   []string{"Épaules au-dessus des coudes.", "Le bassin ne s'affaisse pas.", "Ventre gainé.", "Regard vers le sol."},
		Wrong:     []string{"Creuser le bas du dos.", "Lever le bassin comme un toit.", "Regarder devant.", "Retenir sa respiration."},
		Breathing: "Inspire court, expire long et calme.",
		Voice:     Voice{Start: "Planche. Corps en une ligne.", Mid: []string{"Ventre gainé.", "Le dos ne s'affaisse pas."}, Last: "Cinq secondes.", Finish: "Pose les genoux."},
	},
	"C03": {
		Desc:    "Exercice pour les abdominaux et le contrôle du bas du dos.",
		HowTo:   []string{"Allonge-toi sur le dos.", "Plaque le bas du dos contre le tapis.", "Lève les jambes.", "Petits battements alternés haut-bas."},
		Correct: []string{"Dos stable.", "Faible amplitude.", "Jambes pas trop basses.", "Respiration régulière."},
		Wrong:   []string{"Cambrer le bas du dos.", "Grands moulinets.", "Tendre la nuque.", "Retenir sa respiration."},
		Safety:  "Si le dos se décolle, monte les jambes ou passe au Dead bug.",
		Voice:   Voice{Start: "Dos plaqué.", Mid: []string{"Faible amplitude.", "Respire régulièrement."}, Last: "Cinq secondes.", Finish: "Repose les jambes lentement."},
	},
	"C04": {
		Desc:      "Exercice sûr pour le tronc profond et la stabilité.",
		HowTo:     []string{"Sur le dos, bras vers le haut.", "Genoux à 90°.", "Descends lentement le bras et la jambe opposés.", "Reviens et répète de l'autre côté."},
		Correct:   []string{"Dos plaqué.", "Mouvement lent.", "Le tronc ne se balance pas.", "Amplitude maîtrisée."},
		Wrong:     []string{"Décoller le dos.", "Aller vite.", "Trop descendre la jambe.", "Perdre le contrôle du bassin."},
		Breathing: "Expire en tendant le bras et la jambe.",
		Voice:     Voice{Start: "Dead bug. Dos plaqué.", Mid: []string{"Bouge lentement.", "Le tronc ne se balance pas."}, Finish: "Bien. Ramène les jambes."},
	},
	"C05": {
		Desc:    "Exercice pour les abdominaux latéraux et la stabilité.",
		HowTo:   []string{"Allonge-toi sur le côté.", "Coude sous l'épaule.", "Lève le bassin.", "Garde le corps en une ligne."},
		Correct: []string{"Coude sous l'épaule.", "Bassin levé.", "Le corps ne penche pas.", "Nuque neutre."},
		Wrong:   []string{"Laisser tomber le bassin.", "Coller l'épaule à l'oreille.", "Tourner le tronc vers le bas.", "Retenir sa respiration."},
		Safety:  "Si l'épaule fait mal, réduis le temps de moitié ou fais la planche normale.",
		Voice:   Voice{Start: "Planche latérale. Coude sous l'épaule.", Mid: []string{"Garde le bassin haut.", "Nuque libre."}, Last: "Cinq secondes.", Finish: "Descends en douceur."},
	},
	"C06": {
		Desc:    "Exercice de contrôle pour les abdominaux ; plus doux que les ciseaux.",
		HowTo:   []string{"Sur le dos, jambes à 90°.", "Descends lentement un talon vers le sol.", "Ramène la jambe.", "Répète avec l'autre jambe."},
		Correct: []string{"Le dos ne se décolle pas.", "Mouvement lent.", "Bassin stable.", "Le talon effleure le sol."},
		Wrong:   []string{"Laisser tomber la jambe.", "Cambrer le bas du dos.", "Bouger les deux jambes à la fois.", "Se précipiter."},
		Voice:   Voice{Start: "Toe taps. Lentement.", Mid: []string{"Dos sur le tapis.", "Contact léger."}, Finish: "Relâche le ventre."},
	},
	"C07": {
		Desc:    "Exercice statique pour les abdominaux et le contrôle du tronc.",
		HowTo:   []string{"Sur le dos, dos plaqué.", "Lève un peu les épaules.", "Jambes pliées ou un peu levées.", "Tiens la position."},
		Correct: []string{"Dos au sol.", "Ventre gainé.", "La nuque ne se projette pas.", "Sans retenir sa respiration."},
		Wrong:   []string{"Cambrer le bas du dos.", "Lever le menton.", "Jambes trop basses.", "Supporter la douleur de dos."},
		Safety:  "Si le dos tire, plie les genoux ou passe au Dead bug.",
		Voice:   Voice{Start: "Hollow hold. Dos plaqué.", Mid: []string{"Respire régulièrement.", "Si le dos tire, plie les genoux."}, Last: "Cinq secondes.", Finish: "Pose les épaules et les jambes."},
	},
	"C08": {
		Desc:      "Planche courte et intense avec un gainage maximal.",
		HowTo:     []string{"Mets-toi en planche sur les avant-bras.", "Coudes sous les épaules.", "Gaine le ventre et les fessiers.", "Tire les coudes vers la pointe des pieds."},
		Correct:   []string{"Forte tension abdominale.", "Fessiers engagés.", "Corps droit.", "Respire sans bloquer."},
		Wrong:     []string{"Tenir comme une planche molle.", "Creuser le bas du dos.", "Retenir sa respiration.", "Tenir trop longtemps."},
		Breathing: "Respirations courtes, sans bloquer.",
		Safety:    "Si c'est trop dur, planche normale de 45 à 60 secondes.",
		Voice:     Voice{Start: "Gaine le ventre et les fessiers.", Mid: []string{"Coudes vers la pointe des pieds.", "Tout le corps gainé."}, Last: "Cinq secondes.", Finish: "Pose les genoux."},
	},
	"B01": {
		Desc:    "Exercice pour le dos, les fessiers et la chaîne postérieure.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Bras devant ou le long du corps.", "Lève un peu la poitrine et les jambes.", "Redescends avec contrôle."},
		Correct: []string{"Petite élévation.", "La nuque suit la ligne du dos.", "Fessiers un peu engagés.", "Sans à-coup."},
		Wrong:   []string{"Casser fort le dos.", "Lever la tête.", "Trop lever les jambes.", "Faire des à-coups."},
		Voice:   Voice{Start: "Barque. Petite élévation.", Mid: []string{"Nuque neutre.", "Ne casse pas le dos."}, Finish: "Descends en douceur."},
	},
	"B02": {
		Desc:    "Exercice pour le haut du dos, les omoplates et l'arrière de l'épaule.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Lève un peu la poitrine ou laisse-la au sol.", "Amène les bras en arc au-dessus de la tête.", "Ramène les bras."},
		Correct: []string{"Nuque détendue.", "Les omoplates travaillent.", "Amplitude confortable.", "Sans surcharger le dos."},
		Wrong:   []string{"Lever la tête.", "Se cambrer de trop.", "Tirer sur les bras.", "Épaules aux oreilles."},
		Voice:   Voice{Start: "Bras en arc. Tête baissée.", Mid: []string{"Les omoplates travaillent.", "Ne tends pas la nuque."}, Finish: "Relâche les bras."},
	},
	"B03": {
		Desc:    "Maintien statique pour le dos et les fessiers.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Lève un peu la poitrine et les jambes.", "Tiens la position.", "Respire régulièrement."},
		Correct: []string{"Élévation modérée.", "Nuque neutre.", "Fessiers engagés.", "Respiration régulière."},
		Wrong:   []string{"Lever la tête.", "Se cambrer fort.", "Retenir sa respiration.", "Supporter la douleur de dos."},
		Safety:  "Si le dos gêne, fais la Barque avec moins d'amplitude.",
		Voice:   Voice{Start: "Tiens la barque.", Mid: []string{"Respire régulièrement.", "Nuque longue."}, Last: "Cinq secondes.", Finish: "Descends en douceur."},
	},
	"B04": {
		Desc:    "Exercice pour le haut du dos, les omoplates et l'arrière de l'épaule.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Plie les bras en forme de 'W'.", "Lève un peu les coudes et les mains.", "Rapproche les omoplates et redescends."},
		Correct: []string{"Petit mouvement.", "Les omoplates travaillent.", "La tête regarde le sol.", "Épaules loin des oreilles."},
		Wrong:   []string{"Lever la tête.", "Trop lever les bras.", "Tendre la nuque.", "Cambrer le bas du dos."},
		Voice:   Voice{Start: "Élévation en W. Omoplates en arrière.", Mid: []string{"Tête baissée.", "Petit mouvement."}, Finish: "Abaisse les bras."},
	},
	"B05": {
		Desc:    "Exercice pour le haut du dos, les épaules et le trapèze inférieur.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Tends les bras en diagonale en forme de 'Y'.", "Lève un peu les bras du sol.", "Redescends."},
		Correct: []string{"Les bras se lèvent peu.", "Omoplates basses et en arrière.", "Nuque neutre.", "Dos calme."},
		Wrong:   []string{"Balancement brusque.", "Lever la tête.", "Épaules aux oreilles.", "Se cambrer fort."},
		Voice:   Voice{Start: "Élévation en Y. Bras en diagonale.", Mid: []string{"Épaules loin des oreilles.", "Petite élévation."}, Finish: "Relâche le dos."},
	},
	"G01": {
		Desc:    "Exercice pour les fessiers, l'arrière de la jambe et la stabilité du bassin.",
		HowTo:   []string{"Sur le dos, genoux pliés.", "Pieds au sol.", "Lève le bassin vers le haut.", "En haut, serre les fessiers et redescends lentement."},
		Correct: []string{"Poussée par les talons.", "Bassin jusqu'à une ligne droite.", "Les fessiers travaillent.", "Le dos ne se cambre pas trop."},
		Wrong:   []string{"Cambrer le dos en haut.", "Pieds trop rapprochés.", "Lever les talons.", "Monter le bassin d'un à-coup."},
		Voice:   Voice{Start: "Pont. Pousse par les talons.", Mid: []string{"En haut, serre les fessiers.", "Ne cambre pas le dos."}, Finish: "Descends le bassin lentement."},
	},
	"G02": {
		Desc:    "Pont fessier avec maintien en haut.",
		HowTo:   []string{"Lève le bassin vers le haut.", "Tiens en haut.", "Serre les fessiers.", "Redescends lentement."},
		Correct: []string{"Maintien stable.", "Fessiers engagés.", "Les côtes ne ressortent pas.", "Descente lente."},
		Wrong:   []string{"Trop cambrer le dos.", "Perdre les pieds.", "Laisser tomber le bassin.", "Retenir sa respiration."},
		Voice:   Voice{Start: "Pont avec maintien. Monte et tiens.", Mid: []string{"Les fessiers travaillent.", "Descends lentement."}, Finish: "Relâche les jambes."},
	},
	"L01": {
		Desc:    "Squat peu profond pour les jambes et les fessiers, avec peu de charge sur le genou.",
		HowTo:   []string{"Pieds un peu plus larges que les hanches.", "Pousse le bassin vers l'arrière.", "Plie peu les genoux.", "Remonte par les pieds."},
		Correct: []string{"Faible profondeur.", "Genoux dans l'axe des orteils.", "Talons au sol.", "Dos plat."},
		Wrong:   []string{"Descendre trop bas.", "Laisser les genoux rentrer.", "Lever les talons.", "Se laisser tomber."},
		Safety:  "Si le genou fait mal, passe tout de suite au pont fessier.",
		Voice:   Voice{Start: "Mini-squat. Peu profond.", Mid: []string{"Bassin en arrière.", "Genoux dans l'axe des orteils."}, Finish: "Bien. Ne descends pas trop."},
	},
	"A01": {
		Desc:    "Exercice de biceps sans matériel : un bras oppose une résistance.",
		HowTo:   []string{"Plie au coude le bras qui travaille.", "Avec l'autre main, appuie vers le bas sur l'avant-bras.", "Le bras qui travaille monte lentement.", "Garde la résistance sur tout le trajet."},
		Correct: []string{"Mouvement lent.", "Résistance ressentie.", "Coude près du corps.", "L'épaule ne monte pas."},
		Wrong:   []string{"Le faire sans résistance.", "Tirer sur le bras.", "Lever l'épaule.", "Retenir sa respiration."},
		Voice:   Voice{Start: "Biceps. Un bras résiste à l'autre.", Mid: []string{"Monte lentement.", "Garde la résistance."}, Finish: "Change de bras."},
	},
	"A02": {
		Desc:    "Maintien statique de biceps sans matériel.",
		HowTo:   []string{"Plie à environ 90° le bras qui travaille.", "Avec l'autre main, appuie vers le bas.", "Le bras qui travaille oppose une résistance.", "Garde la tension sans bouger."},
		Correct: []string{"Coude à environ 90°.", "Tension stable.", "Épaules basses.", "Respiration régulière."},
		Wrong:   []string{"Appuyer par à-coups.", "Retenir sa respiration.", "Lever l'épaule.", "Tordre le tronc."},
		Voice:   Voice{Start: "Maintien biceps. Appuie l'un contre l'autre.", Mid: []string{"Épaules basses.", "Respire, ne bloque pas."}, Last: "Cinq secondes.", Finish: "Change de bras."},
	},
	"S01": {
		Desc:    "Exercice pour les épaules, les deltoïdes et le haut du dos.",
		HowTo:   []string{"Ouvre les bras à hauteur d'épaules.", "Fais de petits cercles.", "Garde les épaules basses.", "Garde le tronc droit."},
		Correct: []string{"Petite amplitude.", "Bras stables.", "Nuque détendue.", "Respiration régulière."},
		Wrong:   []string{"Grands moulinets.", "Tendre la nuque.", "Lever les épaules.", "Cambrer le dos."},
		Voice:   Voice{Start: "Petits cercles de bras.", Mid: []string{"Épaules basses.", "Petits cercles."}, Last: "Cinq secondes.", Finish: "Abaisse les bras."},
	},

	// ---- Retour au calme ----
	"CD01": {
		Desc:    "Faire baisser le pouls et se détendre après l'entraînement.",
		HowTo:   []string{"Allonge-toi sur le dos.", "Relâche les épaules.", "Inspire calmement.", "Expire lentement."},
		Correct: []string{"Respiration calme.", "Épaules détendues.", "Le ventre bouge doucement.", "Pas de tension dans la nuque."},
		Wrong:   []string{"Retenir sa respiration.", "Crisper le visage.", "Cambrer le dos.", "Se précipiter."},
		Voice:   Voice{Start: "Respire calmement.", Mid: []string{"Expire longuement."}, Finish: "On passe aux étirements."},
	},
	"CD02": {
		Desc:    "Ouvrir doucement la poitrine et l'avant de l'épaule.",
		HowTo:   []string{"Allonge-toi sur le dos.", "Ouvre les bras sur les côtés.", "Relâche les épaules.", "Respire calmement."},
		Correct: []string{"La poitrine s'ouvre en douceur.", "Épaules sans tension.", "Dos calme.", "Pas de douleur à l'épaule."},
		Wrong:   []string{"Tirer sur les bras jusqu'à la douleur.", "Cambrer le dos.", "Lever les épaules.", "Retenir sa respiration."},
		Voice:   Voice{Start: "Bras sur les côtés. Poitrine ouverte.", Mid: []string{"Ne tire pas jusqu'à la douleur."}, Finish: "Ramène les bras lentement."},
	},
	"CD03": {
		Desc:    "Étirement doux du tronc et de la zone dorso-lombaire.",
		HowTo:   []string{"Sur le dos, genoux pliés.", "Descends doucement les genoux d'un côté.", "Laisse les épaules sur le tapis.", "Répète de l'autre côté."},
		Correct: []string{"Mouvement doux.", "Les épaules ne se lèvent pas.", "Pas de douleur de dos.", "Respiration régulière."},
		Wrong:   []string{"Forcer les genoux au sol.", "Rotation brusque.", "Lever une épaule.", "Supporter la douleur."},
		Voice:   Voice{Start: "Genoux doucement d'un côté.", Mid: []string{"Épaules au sol."}, Finish: "Reviens par le centre."},
	},
	"CD04": {
		Desc:    "Étirement doux de l'arrière de la jambe après l'effort.",
		HowTo:   []string{"Sur le dos, lève une jambe.", "Tiens la cuisse ou le tibia.", "Amène la jambe doucement vers toi.", "Répète avec l'autre jambe."},
		Correct: []string{"Le genou peut être un peu plié.", "Dos calme.", "Étirement doux.", "Respiration régulière."},
		Wrong:   []string{"Tirer la jambe avec force.", "Amener le pied vers le visage.", "Lever le bassin.", "Supporter la douleur derrière le genou."},
		Voice:   Voice{Start: "Lève la jambe. Tire doucement.", Mid: []string{"Pas jusqu'à la douleur."}, Finish: "Change de côté en douceur."},
	},
	"CD05": {
		Desc:    "Étirement de la zone fessière et de l'arrière du bassin.",
		HowTo:   []string{"Allonge-toi sur le dos.", "Pose un pied sur l'autre cuisse.", "Amène la cuisse doucement vers toi.", "N'appuie pas sur le genou."},
		Correct: []string{"Sensation dans le fessier.", "Le genou ne fait pas mal.", "Dos calme.", "Mouvement doux."},
		Wrong:   []string{"Appuyer sur le genou avec la main.", "Forcer jusqu'à la douleur.", "Tordre le bassin.", "Retenir sa respiration."},
		Safety:  "Si le genou gêne, fais un étirement de fessier doux allongé.",
		Voice:   Voice{Start: "Figure quatre. N'appuie pas sur le genou.", Mid: []string{"Amène doucement vers toi."}, Finish: "Change de côté en douceur."},
	},
	"CD06": {
		Desc:    "Ouvrir doucement l'avant du corps et la colonne dorsale.",
		HowTo:   []string{"Allonge-toi sur le ventre.", "Pose les avant-bras au sol.", "Lève doucement la poitrine.", "Garde la nuque longue."},
		Correct: []string{"Élévation douce.", "Coudes sous les épaules ou un peu devant.", "Épaules sans tension.", "Dos sans douleur."},
		Wrong:   []string{"Basculer la tête en arrière.", "Se cambrer de trop.", "Crisper les épaules.", "Supporter la douleur de dos."},
		Voice:   Voice{Start: "Posture du sphinx. Élévation douce.", Mid: []string{"Nuque longue."}, Finish: "Redescends sur le tapis."},
	},
}
