package content

// detailsDE is the German rich content + voice for every exercise.
var detailsDE = map[string]Detail{
	// ---- Aufwärmen ----
	"W01": {
		Desc:    "Ein sanfter Start: Atmung, Wirbelsäulenstreckung und Haltung.",
		HowTo:   []string{"Steh aufrecht, Füße hüftbreit.", "Beim Einatmen sanft über den Scheitel nach oben strecken.", "Die Arme über die Seiten heben.", "Beim Ausatmen die Schultern senken, den Nacken lösen."},
		Correct: []string{"Füße stehen fest am Boden.", "Schultern steigen nicht zu den Ohren.", "Langer Nacken.", "Ruhige Atmung."},
		Wrong:   []string{"Den Kopf nach hinten kippen.", "Den unteren Rücken überstrecken.", "Die Schultern heben.", "Die Luft anhalten."},
		Voice:   Voice{Start: "Steh aufrecht. Ruhig atmen.", Mid: []string{"Über den Scheitel strecken."}, Finish: "Schultern runter. Weiter."},
	},
	"W02": {
		Desc:    "Mobilisierung des Nackens vor dem Training.",
		HowTo:   []string{"Aufrecht stehen.", "Den Kopf langsam nach rechts drehen.", "Zur Mitte zurück.", "Den Kopf nach links drehen."},
		Correct: []string{"Langsame Bewegung.", "Schultern bleiben unten.", "Der Rumpf dreht sich nicht.", "Angenehmer Bereich."},
		Wrong:   []string{"Ruckartige Bewegungen.", "Den Kopf nach hinten kippen.", "Die Schultern heben.", "Den Nacken über Schmerz dehnen."},
		Voice:   Voice{Start: "Wir drehen den Kopf.", Mid: []string{"Sanft, ohne Ruck."}, Finish: "Kopf zur Mitte."},
	},
	"W03": {
		Desc:    "Aufwärmen der Schultergelenke und des oberen Rückens.",
		HowTo:   []string{"Aufrecht stehen.", "Die Schultern etwas heben.", "Nach hinten führen.", "Senken und den Kreis wiederholen."},
		Correct: []string{"Schultern bewegen sich weich.", "Arme entspannt.", "Nacken bleibt frei.", "Stabiler Rumpf."},
		Wrong:   []string{"Mit den Schultern rucken.", "Sich krümmen.", "Den Nacken anspannen.", "Zu großer Bereich."},
		Voice:   Voice{Start: "Schulterkreisen rückwärts.", Mid: []string{"Freier Nacken."}, Finish: "Schultern senken."},
	},
	"W04": {
		Desc:    "Mehr Mobilität für Schultern und oberen Rücken.",
		HowTo:   []string{"Aufrecht stehen.", "Die Schultern vorwärts kreisen.", "Den Nacken frei halten.", "Den Rumpf nicht schaukeln."},
		Correct: []string{"Kontrollierte Bewegung.", "Schultern nicht verspannt.", "Gleichmäßige Atmung.", "Rumpf schaukelt nicht."},
		Wrong:   []string{"Schultern zu den Ohren.", "Ruckartig bewegen.", "Den Rücken runden.", "Die Luft anhalten."},
		Voice:   Voice{Start: "Kreisen vorwärts.", Mid: []string{"Nacken nicht verspannen."}, Finish: "Schultern lösen."},
	},
	"W05": {
		Desc:    "Aufwärmen von Schultern, Deltas und oberem Rücken.",
		HowTo:   []string{"Arme auf Schulterhöhe zur Seite.", "Kleine Kreise vorwärts.", "Schultern unten halten.", "Die Luft nicht anhalten."},
		Correct: []string{"Kleine Kreise.", "Arme auf Schulterhöhe.", "Entspannter Nacken.", "Rumpf schaukelt nicht."},
		Wrong:   []string{"Große Schwünge.", "Schultern zu den Ohren.", "Den Rücken überstrecken.", "Den Nacken anspannen."},
		Voice:   Voice{Start: "Arme zur Seite. Kleine Kreise.", Mid: []string{"Schultern runter."}, Finish: "Arme senken."},
	},
	"W06": {
		Desc:    "Aufwärmen der Schultern und Schulterblatt-Stabilisatoren.",
		HowTo:   []string{"Arme zur Seite.", "Kleine Kreise rückwärts.", "Die Schultern nicht heben.", "Den Rumpf gerade halten."},
		Correct: []string{"Kurze Bewegung.", "Schultern unten.", "Schulterblätter arbeiten sanft.", "Ruhige Atmung."},
		Wrong:   []string{"Ruckeln.", "Weite Schwünge.", "Sich krümmen.", "Den Nacken anspannen."},
		Voice:   Voice{Start: "Kreise rückwärts.", Mid: []string{"Kleiner Bereich."}, Finish: "Arme lösen."},
	},
	"W07": {
		Desc:    "Aktiviert den oberen Rücken und öffnet den Brustkorb.",
		HowTo:   []string{"Aufrecht stehen.", "Die Arme etwas nach hinten.", "Die Schulterblätter sanft zusammenführen.", "Zur Neutralstellung zurück."},
		Correct: []string{"Die Brust öffnet sich.", "Schultern bleiben unten.", "Schulterblätter arbeiten sanft.", "Der Rücken überstreckt nicht."},
		Wrong:   []string{"Den Rücken nach hinten knicken.", "Das Kinn heben.", "Die Arme reißen.", "Die Schultern heben."},
		Voice:   Voice{Start: "Brust öffnen.", Mid: []string{"Schulterblätter sanft nach hinten."}, Finish: "Zur Mitte zurück."},
	},
	"W08": {
		Desc:    "Sanfte Mobilität für die Brustwirbelsäule und den Rumpf.",
		HowTo:   []string{"Aufrecht stehen.", "Den Rumpf nach rechts drehen.", "Zur Mitte zurück.", "Den Rumpf nach links drehen."},
		Correct: []string{"Bewegung kommt aus dem Rumpf.", "Becken fast still.", "Füße drehen nicht.", "Angenehmer Bereich."},
		Wrong:   []string{"Den Rumpf ruckartig drehen.", "Die Knie verdrehen.", "Die Füße reißen.", "Nach hinten fallen."},
		Voice:   Voice{Start: "Rumpfdrehungen.", Mid: []string{"Füße fest."}, Finish: "Zur Mitte zurück."},
	},
	"W09": {
		Desc:    "Wärmt Hüfte und Beinrückseite; lehrt das Beugen ohne runden Rücken.",
		HowTo:   []string{"Aufrecht stehen, Knie leicht weich.", "Das Becken nach hinten schieben.", "Den Rumpf mit geradem Rücken beugen.", "Wieder hochkommen."},
		Correct: []string{"Flacher Rücken.", "Bewegung startet aus der Hüfte.", "Knie leicht weich.", "Nacken folgt der Rückenlinie."},
		Wrong:   []string{"Den Rücken runden.", "Daraus eine Kniebeuge machen.", "Mit Gewalt nach unten greifen.", "Den Kopf heben."},
		Voice:   Voice{Start: "Hüfte zurück, Rücken gerade.", Mid: []string{"Den Rücken nicht runden."}, Finish: "Ruhig aufrichten."},
	},
	"W10": {
		Desc:    "Aufwärmen von Füßen, Waden und Gleichgewicht.",
		HowTo:   []string{"Aufrecht stehen.", "Auf die Zehen heben.", "Kurz halten.", "Langsam senken."},
		Correct: []string{"Körper senkrecht.", "Weiche Bewegung.", "Füße stabil.", "Knie fallen nicht nach innen."},
		Wrong:   []string{"Die Fersen fallen lassen.", "Schaukeln.", "Auf die Fußaußenkante kippen.", "Ruckeln."},
		Voice:   Voice{Start: "Auf die Zehen heben.", Mid: []string{"Langsam senken."}, Finish: "Füße stabil."},
	},

	// ---- Hauptteil ----
	"M01": {
		Desc:      "Grundübung für Brust, Trizeps, Schultern und Rumpf.",
		HowTo:     []string{"Hände unter oder etwas breiter als die Schultern.", "Beine gestreckt, Körper gerade.", "Langsam absenken.", "Ohne Ruck nach oben drücken."},
		Correct:   []string{"Gerader Körper.", "Bauch fest.", "Ellbogen nicht ganz zur Seite.", "Kontrollierte Bewegung."},
		Wrong:     []string{"Den unteren Rücken durchhängen lassen.", "Das Becken heben.", "Nach unten fallen.", "Ellbogen auf 90° spreizen."},
		Breathing: "Beim Absenken ein, beim Hochkommen aus.",
		Voice:     Voice{Start: "Körper gerade. Los geht's.", Mid: []string{"Bauch fest.", "Ellbogen nicht zu weit."}, Finish: "Fertig. Schultern lösen."},
	},
	"M02": {
		Desc:      "Eine Liegestütz-Variante mit mehr Trizeps-Fokus.",
		HowTo:     []string{"Hände etwa unter den Schultern.", "Ellbogen nach hinten, nah am Körper.", "Langsam absenken.", "Ohne Ruck hochdrücken."},
		Correct:   []string{"Gerader Körper.", "Ellbogen spreizen nicht.", "Schultern nicht verspannt.", "Handgelenke schmerzfrei."},
		Wrong:     []string{"Hände zu eng setzen.", "Die Handgelenke knicken.", "Die Ellbogen spreizen.", "Die Körperlinie verlieren."},
		Breathing: "Beim Absenken ein, beim Hochkommen aus.",
		Safety:    "Bei Ellbogen- oder Handgelenkschmerz auf normale Liegestütze mit weniger Wdh.",
		Voice:     Voice{Start: "Enge Liegestütze. Ellbogen nah.", Mid: []string{"Kein Druck auf die Handgelenke.", "Körper gerade."}, Finish: "Gut. Schultern lösen."},
	},
	"M03": {
		Desc:      "Liegestütze mit Kontrolle im tiefsten Punkt.",
		HowTo:     []string{"In die Liegestützposition gehen.", "Langsam absenken.", "1 Sekunde halten.", "Hochdrücken."},
		Correct:   []string{"Kontrollierte Pause.", "Körper hängt nicht durch.", "Ellbogen unter Kontrolle.", "Kein Fallen."},
		Wrong:     []string{"Nach unten fallen.", "Unten entspannen.", "Die Luft anhalten.", "Den Rücken überstrecken."},
		Breathing: "Ein, kurze Pause, beim Hochkommen aus.",
		Voice:     Voice{Start: "Langsam runter. Unten halten.", Mid: []string{"Nicht fallen, kontrollieren.", "Rücken hängt nicht durch."}, Finish: "Super. Pause."},
	},
	"C01": {
		Desc:    "Übung für Bauch und Beckenkontrolle.",
		HowTo:   []string{"Auf den Rücken legen.", "Den unteren Rücken zur Matte drücken.", "Die Beine heben.", "Mit kurzem Bereich kreuzen."},
		Correct: []string{"Rücken auf der Matte.", "Beine nicht zu tief.", "Nacken entspannt.", "Kontrollierte Bewegung."},
		Wrong:   []string{"Den Rücken abheben.", "Die Beine zu tief senken.", "Den Nacken nach vorn ziehen.", "Ruckartige Schwünge."},
		Safety:  "Hebt der Rücken ab, zu Toe taps oder Dead bug wechseln.",
		Voice:   Voice{Start: "Schere. Rücken gedrückt.", Mid: []string{"Beine höher, wenn es im Rücken zieht.", "Nacken entspannt."}, Last: "Noch fünf.", Finish: "Beine sanft absenken."},
	},
	"C02": {
		Desc:      "Statische Übung für Bauch, Schultern, Gesäß und Rumpfstabilität.",
		HowTo:     []string{"Auf Ellbogen und Zehen stützen.", "Ellbogen unter den Schultern.", "Bauch und Gesäß anspannen.", "Eine gerade Körperlinie halten."},
		Correct:   []string{"Schultern über den Ellbogen.", "Becken hängt nicht durch.", "Bauch fest.", "Blick zum Boden."},
		Wrong:     []string{"Den Rücken durchhängen lassen.", "Becken wie ein Dach heben.", "Nach vorn schauen.", "Die Luft anhalten."},
		Breathing: "Kurz ein, lang und ruhig aus.",
		Voice:     Voice{Start: "Plank. Körper in einer Linie.", Mid: []string{"Bauch fest.", "Rücken nicht durchhängen."}, Last: "Noch fünf.", Finish: "Knie absenken."},
	},
	"C03": {
		Desc:    "Übung für Bauch und Kontrolle des unteren Rückens.",
		HowTo:   []string{"Auf den Rücken legen.", "Den unteren Rücken zur Matte drücken.", "Die Beine heben.", "Kurze, wechselnde Auf-ab-Bewegungen."},
		Correct: []string{"Rücken stabil.", "Kurzer Bereich.", "Beine nicht zu tief.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Den Rücken überstrecken.", "Große Schwünge.", "Den Nacken anspannen.", "Die Luft anhalten."},
		Safety:  "Hebt der Rücken ab, Beine höher oder zu Dead bug wechseln.",
		Voice:   Voice{Start: "Rücken gedrückt.", Mid: []string{"Kurzer Bereich.", "Gleichmäßig atmen."}, Last: "Noch fünf.", Finish: "Beine langsam absenken."},
	},
	"C04": {
		Desc:      "Sichere Übung für die tiefe Rumpfmuskulatur und Stabilität.",
		HowTo:     []string{"Auf den Rücken, Arme nach oben.", "Knie 90° gebeugt.", "Gegenüberliegenden Arm und Bein langsam senken.", "Zurück und auf der anderen Seite wiederholen."},
		Correct:   []string{"Rücken gedrückt.", "Langsame Bewegung.", "Rumpf schaukelt nicht.", "Bereich unter Kontrolle."},
		Wrong:     []string{"Den Rücken abheben.", "Schnell bewegen.", "Das Bein zu tief senken.", "Die Beckenkontrolle verlieren."},
		Breathing: "Beim Strecken von Arm und Bein ausatmen.",
		Voice:     Voice{Start: "Dead Bug. Rücken gedrückt.", Mid: []string{"Langsam bewegen.", "Rumpf schaukelt nicht."}, Finish: "Gut. Beine zurück."},
	},
	"C05": {
		Desc:    "Übung für die seitliche Bauchmuskulatur und Stabilität.",
		HowTo:   []string{"Auf die Seite legen.", "Ellbogen unter die Schulter.", "Das Becken heben.", "Den Körper in einer Linie halten."},
		Correct: []string{"Ellbogen unter der Schulter.", "Becken gehoben.", "Körper kippt nicht.", "Neutraler Nacken."},
		Wrong:   []string{"Das Becken durchhängen lassen.", "Schulter zum Ohr ziehen.", "Den Rumpf nach unten drehen.", "Die Luft anhalten."},
		Safety:  "Bei Schulterschmerz die Zeit um 50% kürzen oder normale Plank.",
		Voice:   Voice{Start: "Seitstütz. Ellbogen unter der Schulter.", Mid: []string{"Becken oben halten.", "Freier Nacken."}, Last: "Noch fünf.", Finish: "Sanft absenken."},
	},
	"C06": {
		Desc:    "Kontrollübung für den Bauch; sanfter als die Schere.",
		HowTo:   []string{"Auf den Rücken, Beine 90°.", "Eine Ferse langsam zum Boden senken.", "Das Bein zurück.", "Mit dem anderen Bein wiederholen."},
		Correct: []string{"Rücken hebt nicht ab.", "Langsame Bewegung.", "Stabiles Becken.", "Ferse berührt sanft."},
		Wrong:   []string{"Das Bein fallen lassen.", "Den Rücken überstrecken.", "Beide Beine zugleich bewegen.", "Hetzen."},
		Voice:   Voice{Start: "Toe Taps. Langsam.", Mid: []string{"Rücken auf der Matte.", "Sanfte Berührung."}, Finish: "Bauch lösen."},
	},
	"C07": {
		Desc:    "Statische Übung für Bauch und Rumpfkontrolle.",
		HowTo:   []string{"Auf den Rücken, Rücken gedrückt.", "Die Schultern leicht heben.", "Beine gebeugt oder leicht angehoben.", "Die Position halten."},
		Correct: []string{"Rücken am Boden.", "Bauch fest.", "Nacken nicht nach vorn.", "Atmung nicht angehalten."},
		Wrong:   []string{"Den Rücken überstrecken.", "Das Kinn heben.", "Beine zu tief.", "Rückenschmerz aushalten."},
		Safety:  "Zieht es im Rücken, Knie beugen oder Dead bug.",
		Voice:   Voice{Start: "Hollow Hold. Rücken gedrückt.", Mid: []string{"Gleichmäßig atmen.", "Zieht der Rücken, Knie beugen."}, Last: "Noch fünf.", Finish: "Schultern und Beine senken."},
	},
	"C08": {
		Desc:      "Kurze, harte Plank mit maximaler Rumpfspannung.",
		HowTo:     []string{"In die Unterarm-Plank gehen.", "Ellbogen unter den Schultern.", "Bauch und Gesäß anspannen.", "Die Ellbogen Richtung Zehen ziehen."},
		Correct:   []string{"Starke Bauchspannung.", "Gesäß aktiv.", "Gerader Körper.", "Atmen ohne Anhalten."},
		Wrong:     []string{"Wie eine lockere Plank halten.", "Den Rücken durchhängen lassen.", "Die Luft anhalten.", "Zu lange halten."},
		Breathing: "Kurze Atemzüge, ohne Anhalten.",
		Safety:    "Zu schwer — normale Plank 45–60 Sekunden.",
		Voice:     Voice{Start: "Bauch und Gesäß anspannen.", Mid: []string{"Ellbogen zu den Zehen.", "Ganzer Körper fest."}, Last: "Noch fünf.", Finish: "Knie absenken."},
	},
	"B01": {
		Desc:    "Übung für Rücken, Gesäß und hintere Kette.",
		HowTo:   []string{"Auf den Bauch legen.", "Arme nach vorn oder am Körper.", "Brust und Beine leicht heben.", "Kontrolliert absenken."},
		Correct: []string{"Kleines Heben.", "Nacken folgt der Rückenlinie.", "Gesäß leicht aktiv.", "Kein Ruck."},
		Wrong:   []string{"Den Rücken stark knicken.", "Den Kopf heben.", "Die Beine zu hoch heben.", "Ruckeln."},
		Voice:   Voice{Start: "Boot. Kleines Heben.", Mid: []string{"Neutraler Nacken.", "Den Rücken nicht knicken."}, Finish: "Sanft absenken."},
	},
	"B02": {
		Desc:    "Übung für oberen Rücken, Schulterblätter und hintere Schulter.",
		HowTo:   []string{"Auf den Bauch legen.", "Brust leicht heben oder am Boden lassen.", "Arme im Bogen über den Kopf führen.", "Arme zurückführen."},
		Correct: []string{"Nacken entspannt.", "Schulterblätter arbeiten.", "Angenehmer Bereich.", "Rücken nicht überlasten."},
		Wrong:   []string{"Den Kopf heben.", "Zu stark durchbiegen.", "Die Arme reißen.", "Schultern zu den Ohren."},
		Voice:   Voice{Start: "Arme im Bogen. Kopf unten.", Mid: []string{"Schulterblätter arbeiten.", "Nacken nicht anspannen."}, Finish: "Arme lösen."},
	},
	"B03": {
		Desc:    "Statisches Halten für Rücken und Gesäß.",
		HowTo:   []string{"Auf den Bauch legen.", "Brust und Beine leicht heben.", "Die Position halten.", "Gleichmäßig atmen."},
		Correct: []string{"Mäßiges Heben.", "Neutraler Nacken.", "Gesäß aktiv.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Den Kopf heben.", "Stark durchbiegen.", "Die Luft anhalten.", "Rückenschmerz aushalten."},
		Safety:  "Bei Rückenbeschwerden Boot mit kleinerem Bereich.",
		Voice:   Voice{Start: "Boot halten.", Mid: []string{"Gleichmäßig atmen.", "Langer Nacken."}, Last: "Noch fünf.", Finish: "Sanft absenken."},
	},
	"B04": {
		Desc:    "Übung für oberen Rücken, Schulterblätter und hintere Schulter.",
		HowTo:   []string{"Auf den Bauch legen.", "Arme zu einem 'W' beugen.", "Ellbogen und Hände leicht heben.", "Schulterblätter zusammen und senken."},
		Correct: []string{"Kleine Bewegung.", "Schulterblätter arbeiten.", "Kopf schaut nach unten.", "Schultern nicht zu den Ohren."},
		Wrong:   []string{"Den Kopf heben.", "Die Arme zu hoch heben.", "Den Nacken anspannen.", "Den Rücken überstrecken."},
		Voice:   Voice{Start: "W-Heben. Schulterblätter nach hinten.", Mid: []string{"Kopf unten.", "Kleine Bewegung."}, Finish: "Arme senken."},
	},
	"B05": {
		Desc:    "Übung für oberen Rücken, Schultern und unteren Trapez.",
		HowTo:   []string{"Auf den Bauch legen.", "Arme diagonal zu einem 'Y' strecken.", "Die Arme leicht vom Boden heben.", "Zurück senken."},
		Correct: []string{"Arme heben nur wenig.", "Schulterblätter nach unten und hinten.", "Neutraler Nacken.", "Ruhiger Rücken."},
		Wrong:   []string{"Ruckartiges Schwingen.", "Den Kopf heben.", "Schultern zu den Ohren.", "Stark durchbiegen."},
		Voice:   Voice{Start: "Y-Heben. Diagonale Arme.", Mid: []string{"Schultern nicht zu den Ohren.", "Kleines Heben."}, Finish: "Rücken lösen."},
	},
	"G01": {
		Desc:    "Übung für Gesäß, Beinrückseite und Beckenstabilität.",
		HowTo:   []string{"Auf den Rücken, Knie gebeugt.", "Füße am Boden.", "Das Becken nach oben heben.", "Oben das Gesäß anspannen, langsam senken."},
		Correct: []string{"Druck über die Fersen.", "Becken bis zur geraden Linie.", "Gesäß arbeitet.", "Rücken überstreckt nicht."},
		Wrong:   []string{"Oben den Rücken überstrecken.", "Füße zu nah.", "Die Fersen heben.", "Das Becken ruckartig heben."},
		Voice:   Voice{Start: "Brücke. Über die Fersen drücken.", Mid: []string{"Oben das Gesäß anspannen.", "Den Rücken nicht überstrecken."}, Finish: "Becken langsam senken."},
	},
	"G02": {
		Desc:    "Gesäßbrücke mit Halten oben.",
		HowTo:   []string{"Das Becken nach oben heben.", "Oben halten.", "Das Gesäß anspannen.", "Langsam senken."},
		Correct: []string{"Stabiles Halten.", "Gesäß aktiv.", "Rippen nicht herausdrücken.", "Langsames Absenken."},
		Wrong:   []string{"Den Rücken überstrecken.", "Die Füße verlieren.", "Das Becken fallen lassen.", "Die Luft anhalten."},
		Voice:   Voice{Start: "Brücke mit Halten. Hoch und halten.", Mid: []string{"Gesäß arbeitet.", "Langsam senken."}, Finish: "Beine lösen."},
	},
	"L01": {
		Desc:    "Flache Kniebeuge für Beine und Gesäß mit geringer Kniebelastung.",
		HowTo:   []string{"Füße etwas breiter als die Hüfte.", "Das Becken nach hinten schieben.", "Die Knie flach beugen.", "Über die Füße hochkommen."},
		Correct: []string{"Geringe Tiefe.", "Knie in Richtung der Zehen.", "Fersen am Boden.", "Flacher Rücken."},
		Wrong:   []string{"Zu tief gehen.", "Die Knie nach innen fallen lassen.", "Die Fersen heben.", "Nach unten fallen."},
		Safety:  "Bei Knieschmerz sofort zur Gesäßbrücke wechseln.",
		Voice:   Voice{Start: "Mini-Kniebeuge. Flach.", Mid: []string{"Becken nach hinten.", "Knie in Richtung der Zehen."}, Finish: "Gut. Keine Tiefe."},
	},
	"A01": {
		Desc:    "Bizeps-Übung ohne Geräte: ein Arm leistet Widerstand.",
		HowTo:   []string{"Den Arbeitsarm im Ellbogen beugen.", "Mit der anderen Hand auf den Unterarm drücken.", "Der Arbeitsarm hebt sich langsam.", "Den Widerstand den ganzen Weg halten."},
		Correct: []string{"Langsame Bewegung.", "Spürbarer Widerstand.", "Ellbogen nah am Körper.", "Schulter hebt nicht."},
		Wrong:   []string{"Ohne Widerstand machen.", "Den Arm reißen.", "Die Schulter heben.", "Die Luft anhalten."},
		Voice:   Voice{Start: "Bizeps. Ein Arm hält dagegen.", Mid: []string{"Langsam nach oben.", "Widerstand halten."}, Finish: "Arm wechseln."},
	},
	"A02": {
		Desc:    "Statisches Bizeps-Halten ohne Geräte.",
		HowTo:   []string{"Den Arbeitsarm auf etwa 90° beugen.", "Mit der anderen Hand nach unten drücken.", "Der Arbeitsarm leistet Widerstand.", "Die Spannung ohne Bewegung halten."},
		Correct: []string{"Ellbogen etwa 90°.", "Stabile Spannung.", "Schultern unten.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Ruckartig drücken.", "Die Luft anhalten.", "Die Schulter heben.", "Den Rumpf verdrehen."},
		Voice:   Voice{Start: "Bizeps-Halten. Gegeneinander drücken.", Mid: []string{"Schultern unten.", "Atmen, nicht anhalten."}, Last: "Noch fünf.", Finish: "Arm wechseln."},
	},
	"S01": {
		Desc:    "Übung für Schultern, Deltas und oberen Rücken.",
		HowTo:   []string{"Arme auf Schulterhöhe ausbreiten.", "Kleine Kreise machen.", "Schultern unten halten.", "Den Rumpf gerade halten."},
		Correct: []string{"Kleiner Bereich.", "Arme stabil.", "Nacken entspannt.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Große Schwünge.", "Den Nacken anspannen.", "Die Schultern heben.", "Den Rücken überstrecken."},
		Voice:   Voice{Start: "Kleine Armkreise.", Mid: []string{"Schultern unten.", "Kleine Kreise."}, Last: "Noch fünf.", Finish: "Arme senken."},
	},

	// ---- Abwärmen ----
	"CD01": {
		Desc:    "Puls senken und nach dem Training entspannen.",
		HowTo:   []string{"Auf den Rücken legen.", "Die Schultern lösen.", "Ruhig einatmen.", "Langsam ausatmen."},
		Correct: []string{"Ruhige Atmung.", "Schultern entspannt.", "Bauch bewegt sich sanft.", "Keine Nackenspannung."},
		Wrong:   []string{"Die Luft anhalten.", "Das Gesicht anspannen.", "Den Rücken überstrecken.", "Hetzen."},
		Voice:   Voice{Start: "Ruhig atmen.", Mid: []string{"Lang ausatmen."}, Finish: "Weiter zur Dehnung."},
	},
	"CD02": {
		Desc:    "Sanftes Öffnen von Brust und vorderer Schulter.",
		HowTo:   []string{"Auf den Rücken legen.", "Die Arme zur Seite ausbreiten.", "Die Schultern lösen.", "Ruhig atmen."},
		Correct: []string{"Brust öffnet sanft.", "Schultern nicht verspannt.", "Ruhiger Rücken.", "Kein Schulterschmerz."},
		Wrong:   []string{"Die Arme über Schmerz ziehen.", "Den Rücken überstrecken.", "Die Schultern heben.", "Die Luft anhalten."},
		Voice:   Voice{Start: "Arme zur Seite. Brust offen.", Mid: []string{"Nicht über Schmerz dehnen."}, Finish: "Arme langsam zurück."},
	},
	"CD03": {
		Desc:    "Sanfte Dehnung von Rumpf und Lenden-Brust-Bereich.",
		HowTo:   []string{"Auf den Rücken, Knie gebeugt.", "Die Knie sanft zur Seite senken.", "Die Schultern auf der Matte lassen.", "Auf der anderen Seite wiederholen."},
		Correct: []string{"Sanfte Bewegung.", "Schultern heben nicht.", "Kein Rückenschmerz.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Die Knie mit Kraft zum Boden drücken.", "Scharfe Drehung.", "Eine Schulter abheben.", "Schmerz aushalten."},
		Voice:   Voice{Start: "Knie sanft zur Seite.", Mid: []string{"Schultern am Boden."}, Finish: "Über die Mitte zurück."},
	},
	"CD04": {
		Desc:    "Sanfte Dehnung der Beinrückseite nach der Belastung.",
		HowTo:   []string{"Auf den Rücken, ein Bein heben.", "Oberschenkel oder Schienbein fassen.", "Das Bein sanft zu sich ziehen.", "Mit dem anderen Bein wiederholen."},
		Correct: []string{"Knie darf leicht gebeugt sein.", "Ruhiger Rücken.", "Sanfte Dehnung.", "Gleichmäßige Atmung."},
		Wrong:   []string{"Das Bein mit Kraft ziehen.", "Den Fuß zum Gesicht bringen.", "Das Becken abheben.", "Schmerz hinter dem Knie aushalten."},
		Voice:   Voice{Start: "Bein heben. Sanft ziehen.", Mid: []string{"Nicht über Schmerz."}, Finish: "Seite sanft wechseln."},
	},
	"CD05": {
		Desc:    "Dehnung des Gesäßbereichs und der hinteren Beckenpartie.",
		HowTo:   []string{"Auf den Rücken legen.", "Einen Fuß auf den anderen Oberschenkel legen.", "Den Oberschenkel sanft zu sich ziehen.", "Nicht aufs Knie drücken."},
		Correct: []string{"Gefühl im Gesäß.", "Knie schmerzt nicht.", "Ruhiger Rücken.", "Sanfte Bewegung."},
		Wrong:   []string{"Mit der Hand aufs Knie drücken.", "Über Schmerz ziehen.", "Das Becken verdrehen.", "Die Luft anhalten."},
		Safety:  "Bei Kniebeschwerden eine sanfte liegende Gesäßdehnung.",
		Voice:   Voice{Start: "Figur Vier. Kein Druck aufs Knie.", Mid: []string{"Sanft zu sich ziehen."}, Finish: "Seite sanft wechseln."},
	},
	"CD06": {
		Desc:    "Sanftes Öffnen der Körpervorderseite und der Brustwirbelsäule.",
		HowTo:   []string{"Auf den Bauch legen.", "Die Unterarme auf den Boden.", "Die Brust sanft heben.", "Der Nacken bleibt lang."},
		Correct: []string{"Sanftes Heben.", "Ellbogen unter oder leicht vor den Schultern.", "Schultern nicht verspannt.", "Rücken schmerzfrei."},
		Wrong:   []string{"Den Kopf nach hinten kippen.", "Zu stark durchbiegen.", "Die Schultern anspannen.", "Rückenschmerz aushalten."},
		Voice:   Voice{Start: "Sphinx-Haltung. Sanftes Heben.", Mid: []string{"Langer Nacken."}, Finish: "Auf die Matte senken."},
	},
}
