package content

// detailsTR is the Turkish rich content + voice for every exercise.
var detailsTR = map[string]Detail{
	// ---- Isınma ----
	"W01": {
		Desc:    "Yumuşak başlangıç: nefes, omurga uzaması ve duruş.",
		HowTo:   []string{"Dik dur, ayaklar kalça genişliğinde.", "Nefes alırken başının tepesinden yukarı uzan.", "Kolları yanlardan yukarı kaldırabilirsin.", "Nefes verirken omuzları indir, boynu gevşet."},
		Correct: []string{"Ayaklar yere sağlam basıyor.", "Omuzlar kulaklara yükselmiyor.", "Boyun uzun.", "Sakin nefes."},
		Wrong:   []string{"Başı geriye atmak.", "Beli aşırı çukurlaştırmak.", "Omuzları kaldırmak.", "Nefesi tutmak."},
		Voice:   Voice{Start: "Dik dur. Sakin nefes al.", Mid: []string{"Tependen yukarı uzan."}, Finish: "Omuzlar aşağı. Devam."},
	},
	"W02": {
		Desc:    "Antrenman öncesi boynu hazırlama.",
		HowTo:   []string{"Dik dur.", "Başı yavaşça sağa çevir.", "Ortaya dön.", "Başı sola çevir."},
		Correct: []string{"Hareket yavaş.", "Omuzlar aşağıda kalıyor.", "Gövde dönmüyor.", "Rahat genişlik."},
		Wrong:   []string{"Ani hareketler.", "Başı geriye atmak.", "Omuzları kaldırmak.", "Boynu ağrıyana kadar germek."},
		Voice:   Voice{Start: "Başı çeviriyoruz.", Mid: []string{"Yumuşak, ani değil."}, Finish: "Başı ortaya getir."},
	},
	"W03": {
		Desc:    "Omuz eklemlerini ve üst sırtı ısıtma.",
		HowTo:   []string{"Dik dur.", "Omuzları biraz yukarı kaldır.", "Geriye götür.", "Aşağı indir ve daireyi tekrarla."},
		Correct: []string{"Omuzlar akıcı.", "Kollar gevşek.", "Boyun sıkışmıyor.", "Gövde sabit."},
		Wrong:   []string{"Omuzları sarsmak.", "Kamburlaşmak.", "Boynu germek.", "Çok geniş hareket."},
		Voice:   Voice{Start: "Omuz çevirme, geriye.", Mid: []string{"Boyun serbest."}, Finish: "Omuzları indir."},
	},
	"W04": {
		Desc:    "Omuzlar ve üst sırt için daha fazla hareketlilik.",
		HowTo:   []string{"Dik dur.", "Omuzları ileri çevir.", "Boynu serbest tut.", "Gövdeyi sallama."},
		Correct: []string{"Kontrollü hareket.", "Omuzlar gergin değil.", "Düzenli nefes.", "Gövde sallanmıyor."},
		Wrong:   []string{"Omuzları kulaklara almak.", "Sert hareket.", "Sırtı yuvarlamak.", "Nefesi tutmak."},
		Voice:   Voice{Start: "İleri çevirme.", Mid: []string{"Boynu sıkma."}, Finish: "Omuzları gevşet."},
	},
	"W05": {
		Desc:    "Omuzları, deltoidleri ve üst sırtı ısıtma.",
		HowTo:   []string{"Kolları omuz hizasında yanlara aç.", "İleri doğru küçük daireler çiz.", "Omuzları aşağıda tut.", "Nefesi tutma."},
		Correct: []string{"Küçük daireler.", "Kollar omuz hizasında.", "Boyun gevşek.", "Gövde sallanmıyor."},
		Wrong:   []string{"Büyük savurmalar.", "Omuzları kulaklara almak.", "Beli çukurlaştırmak.", "Boynu germek."},
		Voice:   Voice{Start: "Kollar yanlara. Küçük daireler.", Mid: []string{"Omuzlar aşağı."}, Finish: "Kolları indir."},
	},
	"W06": {
		Desc:    "Omuzları ve kürek kemiği stabilizatörlerini ısıtma.",
		HowTo:   []string{"Kollar yanlara.", "Geriye küçük daireler çiz.", "Omuzları kaldırma.", "Gövdeyi düz tut."},
		Correct: []string{"Kısa hareket.", "Omuzlar aşağıda.", "Kürekler yumuşak çalışıyor.", "Sakin nefes."},
		Wrong:   []string{"Sarsıntılar.", "Geniş savurma.", "Kamburlaşmak.", "Boynu sıkmak."},
		Voice:   Voice{Start: "Geriye daireler.", Mid: []string{"Küçük genlik."}, Finish: "Kolları gevşet."},
	},
	"W07": {
		Desc:    "Üst sırtı çalıştırır ve göğsü açar.",
		HowTo:   []string{"Dik dur.", "Kolları hafifçe geriye al.", "Kürek kemiklerini yumuşakça sık.", "Nötr duruşa dön."},
		Correct: []string{"Göğüs açılıyor.", "Omuzlar aşağıda.", "Kürekler yumuşak çalışıyor.", "Bel çukurlaşmıyor."},
		Wrong:   []string{"Beli geriye kırmak.", "Çeneyi kaldırmak.", "Kolları sarsmak.", "Omuzları kaldırmak."},
		Voice:   Voice{Start: "Göğsü açıyoruz.", Mid: []string{"Kürekler yumuşakça geriye."}, Finish: "Ortaya dön."},
	},
	"W08": {
		Desc:    "Sırt ortası ve gövde için yumuşak hareketlilik.",
		HowTo:   []string{"Dik dur.", "Gövdeyi sağa çevir.", "Ortaya dön.", "Gövdeyi sola çevir."},
		Correct: []string{"Hareket gövdeden gelir.", "Kalça neredeyse sabit.", "Ayaklar dönmüyor.", "Rahat genişlik."},
		Wrong:   []string{"Gövdeyi sert çevirmek.", "Dizleri burmak.", "Ayakları sarsmak.", "Geriye düşmek."},
		Voice:   Voice{Start: "Gövde dönüşleri.", Mid: []string{"Ayaklar sağlam."}, Finish: "Ortaya dön."},
	},
	"W09": {
		Desc:    "Kalçayı ve arka bacağı ısıtır; sırtı yuvarlamadan eğilmeyi öğretir.",
		HowTo:   []string{"Dik dur, dizleri hafif yumuşat.", "Kalçayı geriye gönder.", "Düz sırtla gövdeyi eğ.", "Yukarı dön."},
		Correct: []string{"Sırt düz.", "Hareket kalçadan başlar.", "Dizler hafif yumuşak.", "Boyun sırt çizgisini sürdürür."},
		Wrong:   []string{"Sırtı yuvarlamak.", "Çömelmeye çevirmek.", "Zorla aşağı uzanmak.", "Başı kaldırmak."},
		Voice:   Voice{Start: "Kalça geriye, sırt düz.", Mid: []string{"Sırtı yuvarlama."}, Finish: "Sakince doğrul."},
	},
	"W10": {
		Desc:    "Ayakları, baldırları ve dengeyi ısıtma.",
		HowTo:   []string{"Dik dur.", "Parmak uçlarına yüksel.", "Bir an bekle.", "Yavaşça in."},
		Correct: []string{"Vücut dik.", "Akıcı hareket.", "Ayaklar sağlam.", "Dizler içe düşmüyor."},
		Wrong:   []string{"Topukları düşürmek.", "Sallanmak.", "Ayağın dış kenarına düşmek.", "Sarsmak."},
		Voice:   Voice{Start: "Parmak uçlarına yüksel.", Mid: []string{"Yavaşça in."}, Finish: "Ayaklar sağlam."},
	},

	// ---- Ana bölüm ----
	"M01": {
		Desc:      "Göğüs, triceps, omuz ve gövde için temel egzersiz.",
		HowTo:     []string{"Eller omuzların altında ya da biraz daha geniş.", "Bacaklar uzanmış, vücut düz.", "Yumuşakça in.", "Sarsmadan yukarı it."},
		Correct:   []string{"Düz vücut.", "Karın sıkı.", "Dirsekler tam yana açılmıyor.", "Kontrollü hareket."},
		Wrong:     []string{"Beli çökertmek.", "Kalçayı kaldırmak.", "Aşağı düşmek.", "Dirsekleri 90°'ye açmak."},
		Breathing: "İnerken al, kalkarken ver.",
		Voice:     Voice{Start: "Vücut düz. Başlıyoruz.", Mid: []string{"Karın sıkı.", "Dirsekler çok geniş değil."}, Finish: "Tamam. Omuzları gevşet."},
	},
	"M02": {
		Desc:      "Triceps ağırlıklı bir şınav çeşidi.",
		HowTo:     []string{"Eller yaklaşık omuz altında.", "Dirsekleri gövdeye yakın, geriye yönlendir.", "Yavaşça in.", "Sarsmadan yukarı it."},
		Correct:   []string{"Vücut düz.", "Dirsekler geniş açılmıyor.", "Omuzlar gergin değil.", "Bilekler ağrımıyor."},
		Wrong:     []string{"Elleri çok yakın koymak.", "Bilekleri bükmek.", "Dirsekleri açmak.", "Vücut çizgisini bozmak."},
		Breathing: "İnerken al, kalkarken ver.",
		Safety:    "Dirsek veya bilek ağrısında daha az tekrarla normal şınava geç.",
		Voice:     Voice{Start: "Dar şınav. Dirsekler yakın.", Mid: []string{"Bileklere bastırma.", "Vücut düz."}, Finish: "İyi. Omuzları gevşet."},
	},
	"M03": {
		Desc:      "Alt noktada kontrollü şınav.",
		HowTo:     []string{"Şınav pozisyonu al.", "Yavaşça in.", "1 saniye bekle.", "Yukarı it."},
		Correct:   []string{"Kontrollü duraklama.", "Vücut çökmüyor.", "Dirsekler kontrol altında.", "Düşme yok."},
		Wrong:     []string{"Aşağı düşmek.", "Altta gevşemek.", "Nefesi tutmak.", "Beli çukurlaştırmak."},
		Breathing: "İnerken al, kısa dur, kalkarken ver.",
		Voice:     Voice{Start: "Yavaşça in. Altta bekle.", Mid: []string{"Düşme, kontrol et.", "Bel çökmesin."}, Finish: "Harika. Dinlen."},
	},
	"C01": {
		Desc:    "Karın ve kalça kontrolü için egzersiz.",
		HowTo:   []string{"Sırtüstü yat.", "Beli mata bastır.", "Bacakları kaldır.", "Kısa genlikle makas yap."},
		Correct: []string{"Bel matta.", "Bacaklar çok aşağıda değil.", "Boyun gevşek.", "Kontrollü hareket."},
		Wrong:   []string{"Beli kaldırmak.", "Bacakları çok aşağı indirmek.", "Boynu öne çekmek.", "Sarsıntılı savurma."},
		Safety:  "Bel kalkıyorsa Toe taps veya Dead bug'a geç.",
		Voice:   Voice{Start: "Makas. Bel bastırılmış.", Mid: []string{"Bel çekiyorsa bacaklar yukarı.", "Boyun gevşek."}, Last: "Beş saniye.", Finish: "Bacakları yavaşça indir."},
	},
	"C02": {
		Desc:      "Karın, omuz, kalça ve gövde stabilizasyonu için statik egzersiz.",
		HowTo:     []string{"Dirsek ve parmak uçlarına gel.", "Dirsekler omuz altında.", "Karnı ve kalçayı sık.", "Düz vücut çizgisini koru."},
		Correct:   []string{"Omuzlar dirsek üstünde.", "Kalça çökmüyor.", "Karın sıkı.", "Bakış yere."},
		Wrong:     []string{"Beli çökertmek.", "Kalçayı çatı gibi kaldırmak.", "Öne bakmak.", "Nefesi tutmak."},
		Breathing: "Kısa al, uzun ve sakin ver.",
		Voice:     Voice{Start: "Plank. Vücut tek çizgi.", Mid: []string{"Karın sıkı.", "Bel çökmesin."}, Last: "Beş saniye.", Finish: "Dizleri indir."},
	},
	"C03": {
		Desc:    "Karın ve bel kontrolü için egzersiz.",
		HowTo:   []string{"Sırtüstü yat.", "Beli mata bastır.", "Bacakları kaldır.", "Kısa, dönüşümlü aşağı-yukarı hareketler."},
		Correct: []string{"Bel sabit.", "Kısa genlik.", "Bacaklar çok aşağıda değil.", "Düzenli nefes."},
		Wrong:   []string{"Beli çukurlaştırmak.", "Büyük savurmalar.", "Boynu germek.", "Nefesi tutmak."},
		Safety:  "Bel kalkıyorsa bacakları yükselt ya da Dead bug'a geç.",
		Voice:   Voice{Start: "Bel bastırılmış.", Mid: []string{"Kısa genlik.", "Düzenli nefes al."}, Last: "Beş saniye.", Finish: "Bacakları yavaş indir."},
	},
	"C04": {
		Desc:      "Derin gövde ve stabilizasyon için güvenli egzersiz.",
		HowTo:     []string{"Sırtüstü yat, kollar yukarı.", "Dizler 90°.", "Karşı kol ve bacağı yavaşça indir.", "Dön ve diğer tarafta tekrarla."},
		Correct:   []string{"Bel bastırılmış.", "Yavaş hareket.", "Gövde sallanmıyor.", "Genlik kontrollü."},
		Wrong:     []string{"Beli kaldırmak.", "Hızlı hareket.", "Bacağı çok aşağı indirmek.", "Kalça kontrolünü kaybetmek."},
		Breathing: "Kol ve bacak uzanırken nefes ver.",
		Voice:     Voice{Start: "Dead bug. Bel bastırılmış.", Mid: []string{"Yavaş hareket et.", "Gövde sallanmıyor."}, Finish: "İyi. Bacakları indir."},
	},
	"C05": {
		Desc:    "Yan karın ve yan stabilizasyon için egzersiz.",
		HowTo:   []string{"Yan yat.", "Dirseği omuz altına koy.", "Kalçayı kaldır.", "Vücudu tek çizgide tut."},
		Correct: []string{"Dirsek omuz altında.", "Kalça yukarıda.", "Gövde yana düşmüyor.", "Boyun nötr."},
		Wrong:   []string{"Kalçayı çökertmek.", "Omzu kulağa sıkıştırmak.", "Gövdeyi aşağı çevirmek.", "Nefesi tutmak."},
		Safety:  "Omuz ağrırsa süreyi %50 azalt ya da normal plank yap.",
		Voice:   Voice{Start: "Yan plank. Dirsek omuz altında.", Mid: []string{"Kalçayı yukarıda tut.", "Boyun serbest."}, Last: "Beş saniye.", Finish: "Yumuşakça in."},
	},
	"C06": {
		Desc:    "Karın için kontrol egzersizi; makasa göre daha yumuşak.",
		HowTo:   []string{"Sırtüstü yat, bacaklar 90°.", "Bir topuğu yavaşça yere indir.", "Bacağı geri getir.", "Diğer bacakla tekrarla."},
		Correct: []string{"Bel kalkmıyor.", "Yavaş hareket.", "Kalça sabit.", "Topuk yumuşak değiyor."},
		Wrong:   []string{"Bacağı aşağı bırakmak.", "Beli çukurlaştırmak.", "İki bacağı aynı anda hareket ettirmek.", "Acele etmek."},
		Voice:   Voice{Start: "Toe taps. Yavaşça.", Mid: []string{"Bel matta.", "Dokunuş yumuşak."}, Finish: "Karnı gevşet."},
	},
	"C07": {
		Desc:    "Karın ve gövde kontrolü için statik egzersiz.",
		HowTo:   []string{"Sırtüstü yat, bel bastırılmış.", "Omuzları hafif kaldır.", "Bacaklar bükülü ya da hafif kalkık.", "Pozisyonu koru."},
		Correct: []string{"Bel yerde.", "Karın sıkı.", "Boyun öne gerilmiyor.", "Nefes tutulmuyor."},
		Wrong:   []string{"Beli çukurlaştırmak.", "Çeneyi kaldırmak.", "Bacaklar çok aşağıda.", "Sırt ağrısına katlanmak."},
		Safety:  "Bel çekiyorsa dizleri bük ya da Dead bug'a geç.",
		Voice:   Voice{Start: "Hollow hold. Bel bastırılmış.", Mid: []string{"Düzenli nefes al.", "Bel çekiyorsa dizleri bük."}, Last: "Beş saniye.", Finish: "Omuz ve bacakları indir."},
	},
	"C08": {
		Desc:      "Maksimum gövde gerilimiyle kısa, sert plank.",
		HowTo:     []string{"Dirsek plankına geç.", "Dirsekler omuz altında.", "Karnı ve kalçayı sık.", "Dirsekleri parmak uçlarına çek."},
		Correct:   []string{"Güçlü karın gerilimi.", "Kalça devrede.", "Vücut düz.", "Nefesi tutmadan."},
		Wrong:     []string{"Gevşek plank gibi tutmak.", "Beli çökertmek.", "Nefesi tutmak.", "Çok uzun durmak."},
		Breathing: "Kısa nefesler, tutmadan.",
		Safety:    "Çok zorsa 45–60 saniye normal plank yap.",
		Voice:     Voice{Start: "Karnı ve kalçayı sık.", Mid: []string{"Dirsekler parmak uçlarına.", "Tüm vücut sıkı."}, Last: "Beş saniye.", Finish: "Dizleri indir."},
	},
	"B01": {
		Desc:    "Sırt, kalça ve arka zincir için egzersiz.",
		HowTo:   []string{"Yüzüstü yat.", "Kolları öne ya da gövde yanına uzat.", "Göğüs ve bacakları hafif kaldır.", "Kontrollü indir."},
		Correct: []string{"Küçük kalkış.", "Boyun sırt çizgisini sürdürür.", "Kalça hafif devrede.", "Sarsma yok."},
		Wrong:   []string{"Beli sert kırmak.", "Başı kaldırmak.", "Bacakları çok yükseltmek.", "Sarsmak."},
		Voice:   Voice{Start: "Kayık. Küçük kalkış.", Mid: []string{"Boyun nötr.", "Beli kırma."}, Finish: "Yumuşakça in."},
	},
	"B02": {
		Desc:    "Üst sırt, kürekler ve arka omuz için egzersiz.",
		HowTo:   []string{"Yüzüstü yat.", "Göğsü hafif kaldır ya da yerde bırak.", "Kolları yay çizerek baş üstüne götür.", "Kolları geri getir."},
		Correct: []string{"Boyun gevşek.", "Kürekler çalışıyor.", "Rahat genlik.", "Bel zorlanmıyor."},
		Wrong:   []string{"Başı kaldırmak.", "Aşırı çukurlaşmak.", "Kolları sarsmak.", "Omuzları kulaklara almak."},
		Voice:   Voice{Start: "Kollar yay çizerek. Baş aşağı.", Mid: []string{"Kürekler çalışıyor.", "Boynu sıkma."}, Finish: "Kolları gevşet."},
	},
	"B03": {
		Desc:    "Sırt ve kalça için statik tutuş.",
		HowTo:   []string{"Yüzüstü yat.", "Göğüs ve bacakları hafif kaldır.", "Pozisyonu tut.", "Düzenli nefes al."},
		Correct: []string{"Ölçülü kalkış.", "Boyun nötr.", "Kalça devrede.", "Düzenli nefes."},
		Wrong:   []string{"Başı kaldırmak.", "Aşırı çukurlaşmak.", "Nefesi tutmak.", "Bel ağrısına katlanmak."},
		Safety:  "Bel rahatsızsa daha küçük genlikle kayık yap.",
		Voice:   Voice{Start: "Kayığı tut.", Mid: []string{"Düzenli nefes al.", "Boyun uzun."}, Last: "Beş saniye.", Finish: "Yumuşakça in."},
	},
	"B04": {
		Desc:    "Üst sırt, kürekler ve arka omuz için egzersiz.",
		HowTo:   []string{"Yüzüstü yat.", "Kolları 'W' biçiminde bük.", "Dirsek ve elleri hafif kaldır.", "Kürekleri sık ve indir."},
		Correct: []string{"Küçük hareket.", "Kürekler çalışıyor.", "Baş aşağı bakıyor.", "Omuzlar kulaklara değil."},
		Wrong:   []string{"Başı kaldırmak.", "Kolları çok yükseltmek.", "Boynu germek.", "Beli çukurlaştırmak."},
		Voice:   Voice{Start: "W kaldırma. Kürekler geriye.", Mid: []string{"Baş aşağı.", "Küçük hareket."}, Finish: "Kolları indir."},
	},
	"B05": {
		Desc:    "Üst sırt, omuz ve alt trapez için egzersiz.",
		HowTo:   []string{"Yüzüstü yat.", "Kolları çapraz 'Y' biçiminde uzat.", "Kolları yerden hafif kaldır.", "Geri indir."},
		Correct: []string{"Kollar az kalkıyor.", "Kürekler aşağı ve geriye.", "Boyun nötr.", "Bel sakin."},
		Wrong:   []string{"Sert savurma.", "Başı kaldırmak.", "Omuzları kulaklara almak.", "Aşırı çukurlaşmak."},
		Voice:   Voice{Start: "Y kaldırma. Çapraz kollar.", Mid: []string{"Omuzlar kulaklara değil.", "Küçük kalkış."}, Finish: "Sırtı gevşet."},
	},
	"G01": {
		Desc:    "Kalça, arka bacak ve pelvis stabilizasyonu için egzersiz.",
		HowTo:   []string{"Sırtüstü yat, dizler bükülü.", "Ayaklar yerde.", "Kalçayı yukarı kaldır.", "Üstte kalçayı sık, yavaş in."},
		Correct: []string{"İtiş topuklardan.", "Kalça düz çizgiye.", "Kalça çalışıyor.", "Bel aşırı açılmıyor."},
		Wrong:   []string{"Üstte beli çukurlaştırmak.", "Ayakları çok yakın koymak.", "Topukları kaldırmak.", "Kalçayı sarsarak kaldırmak."},
		Voice:   Voice{Start: "Köprü. Topuklardan it.", Mid: []string{"Üstte kalçayı sık.", "Beli çukurlaştırma."}, Finish: "Kalçayı yavaş indir."},
	},
	"G02": {
		Desc:    "Üstte tutuşlu kalça köprüsü.",
		HowTo:   []string{"Kalçayı yukarı kaldır.", "Üstte bekle.", "Kalçayı sık.", "Yavaş in."},
		Correct: []string{"Sabit tutuş.", "Kalça devrede.", "Kaburgalar dışarı çıkmıyor.", "İniş yavaş."},
		Wrong:   []string{"Beli aşırı açmak.", "Ayakları kaybetmek.", "Kalçayı düşürmek.", "Nefesi tutmak."},
		Voice:   Voice{Start: "Duraklamalı köprü. Yukarı ve tut.", Mid: []string{"Kalça çalışıyor.", "Yavaş in."}, Finish: "Bacakları gevşet."},
	},
	"L01": {
		Desc:    "Dize az yük binen sığ çömelme.",
		HowTo:   []string{"Ayaklar kalçadan biraz geniş.", "Kalçayı geriye gönder.", "Dizleri sığ bük.", "Ayaklardan yukarı dön."},
		Correct: []string{"Az derinlik.", "Dizler parmak yönünde.", "Topuklar yerde.", "Sırt düz."},
		Wrong:   []string{"Derine inmek.", "Dizleri içe düşürmek.", "Topukları kaldırmak.", "Aşağı düşmek."},
		Safety:  "Diz ağrırsa hemen kalça köprüsüne geç.",
		Voice:   Voice{Start: "Mini çömelme. Sığ.", Mid: []string{"Kalça geriye.", "Dizler parmak yönünde."}, Finish: "İyi. Derine inme."},
	},
	"A01": {
		Desc:    "Aletsiz biceps egzersizi: bir kol diğerine direnç uygular.",
		HowTo:   []string{"Çalışan kolu dirsekten bük.", "Diğer elle ön kola aşağı bastır.", "Çalışan kol yavaşça yükselir.", "Direnci yol boyunca koru."},
		Correct: []string{"Yavaş hareket.", "Hissedilir direnç.", "Dirsek gövdeye yakın.", "Omuz yükselmiyor."},
		Wrong:   []string{"Dirençsiz yapmak.", "Kolu sarsmak.", "Omuzu kaldırmak.", "Nefesi tutmak."},
		Voice:   Voice{Start: "Biceps. Bir kol diğerine direnir.", Mid: []string{"Yavaşça yukarı.", "Direnci koru."}, Finish: "Kolu değiştir."},
	},
	"A02": {
		Desc:    "Aletsiz statik biceps tutuşu.",
		HowTo:   []string{"Çalışan kolu yaklaşık 90° bük.", "Diğer elle aşağı bastır.", "Çalışan kol direnir.", "Hareketsiz gerilimi koru."},
		Correct: []string{"Dirsek yaklaşık 90°.", "Sabit gerilim.", "Omuzlar aşağıda.", "Düzenli nefes."},
		Wrong:   []string{"Sarsarak bastırmak.", "Nefesi tutmak.", "Omuzu kaldırmak.", "Gövdeyi burmak."},
		Voice:   Voice{Start: "Biceps tutuşu. Birbirine bastır.", Mid: []string{"Omuzlar aşağı.", "Nefes al, tutma."}, Last: "Beş saniye.", Finish: "Kolu değiştir."},
	},
	"S01": {
		Desc:    "Omuz, deltoid ve üst sırt için egzersiz.",
		HowTo:   []string{"Kolları omuz hizasında aç.", "Küçük daireler çiz.", "Omuzları aşağıda tut.", "Gövdeyi düz tut."},
		Correct: []string{"Küçük genlik.", "Kollar sabit.", "Boyun gevşek.", "Düzenli nefes."},
		Wrong:   []string{"Büyük savurmalar.", "Boynu sıkmak.", "Omuzları kaldırmak.", "Beli çukurlaştırmak."},
		Voice:   Voice{Start: "Küçük kol daireleri.", Mid: []string{"Omuzlar aşağı.", "Küçük daireler."}, Last: "Beş saniye.", Finish: "Kolları indir."},
	},

	// ---- Soğuma ----
	"CD01": {
		Desc:    "Antrenman sonrası nabzı düşürme ve gevşeme.",
		HowTo:   []string{"Sırtüstü yat.", "Omuzları gevşet.", "Sakin bir nefes al.", "Yavaşça ver."},
		Correct: []string{"Sakin nefes.", "Omuzlar gevşek.", "Karın yumuşak hareket ediyor.", "Boyun gergin değil."},
		Wrong:   []string{"Nefesi tutmak.", "Yüzü germek.", "Beli çukurlaştırmak.", "Acele etmek."},
		Voice:   Voice{Start: "Sakin nefes al.", Mid: []string{"Uzun nefes ver."}, Finish: "Esnemeye geçiyoruz."},
	},
	"CD02": {
		Desc:    "Göğsü ve omuz önünü yumuşak açma.",
		HowTo:   []string{"Sırtüstü yat.", "Kolları yanlara aç.", "Omuzları gevşet.", "Sakin nefes al."},
		Correct: []string{"Göğüs yumuşak açılıyor.", "Omuzlar sıkışmıyor.", "Bel sakin.", "Omuz ağrısı yok."},
		Wrong:   []string{"Kolları ağrıyana kadar germek.", "Beli çukurlaştırmak.", "Omuzları kaldırmak.", "Nefesi tutmak."},
		Voice:   Voice{Start: "Kollar yanlara. Göğüs açık.", Mid: []string{"Ağrıyana kadar germe."}, Finish: "Kolları yavaş geri getir."},
	},
	"CD03": {
		Desc:    "Gövde ve bel-sırt için yumuşak esneme.",
		HowTo:   []string{"Sırtüstü yat, dizler bükülü.", "Dizleri yumuşakça yana indir.", "Omuzları matta bırak.", "Diğer tarafta tekrarla."},
		Correct: []string{"Yumuşak hareket.", "Omuzlar kalkmıyor.", "Bel ağrısı yok.", "Düzenli nefes."},
		Wrong:   []string{"Dizleri zorla yere bastırmak.", "Sert dönüş.", "Bir omuzu kaldırmak.", "Ağrıya katlanmak."},
		Voice:   Voice{Start: "Dizler yumuşakça yana.", Mid: []string{"Omuzlar yerde."}, Finish: "Ortadan geri dön."},
	},
	"CD04": {
		Desc:    "Yükten sonra arka bacağı yumuşak esnetme.",
		HowTo:   []string{"Sırtüstü yat, bir bacağı kaldır.", "Uyluk ya da baldırı tut.", "Bacağı yumuşakça kendine çek.", "Diğer bacakla tekrarla."},
		Correct: []string{"Diz hafif bükülebilir.", "Bel sakin.", "Esneme yumuşak.", "Düzenli nefes."},
		Wrong:   []string{"Bacağı zorla çekmek.", "Ayağı yüze götürmek.", "Kalçayı kaldırmak.", "Diz arkası ağrısına katlanmak."},
		Voice:   Voice{Start: "Bacağı kaldır. Yumuşak çek.", Mid: []string{"Ağrıyana kadar değil."}, Finish: "Tarafı yumuşakça değiştir."},
	},
	"CD05": {
		Desc:    "Kalça bölgesi ve pelvis arkası için esneme.",
		HowTo:   []string{"Sırtüstü yat.", "Bir ayağı diğer uyluğa koy.", "Uyluğu yumuşakça kendine çek.", "Dize bastırma."},
		Correct: []string{"Kalçada his.", "Diz ağrımıyor.", "Bel sakin.", "Yumuşak hareket."},
		Wrong:   []string{"Elle dize bastırmak.", "Ağrıya zorlamak.", "Pelvisi burmak.", "Nefesi tutmak."},
		Safety:  "Dizde rahatsızlık varsa yumuşak kalça esnemesi yap.",
		Voice:   Voice{Start: "Figür dört. Dize bastırma.", Mid: []string{"Yumuşakça kendine çek."}, Finish: "Tarafı yumuşakça değiştir."},
	},
	"CD06": {
		Desc:    "Vücut önünü ve sırt ortasını yumuşak açma.",
		HowTo:   []string{"Yüzüstü yat.", "Ön kolları yere koy.", "Göğsü yumuşakça kaldır.", "Boyun uzun kalsın."},
		Correct: []string{"Yumuşak kalkış.", "Dirsekler omuz altında ya da biraz önde.", "Omuzlar sıkışmıyor.", "Bel ağrısız."},
		Wrong:   []string{"Başı geriye atmak.", "Aşırı çukurlaşmak.", "Omuzları sıkmak.", "Bel ağrısına katlanmak."},
		Voice:   Voice{Start: "Sfenks pozu. Yumuşak kalkış.", Mid: []string{"Boyun uzun."}, Finish: "Mata in."},
	},
}
