package content

// detailsES is the Spanish rich content + voice for every exercise.
var detailsES = map[string]Detail{
	// ---- Calentamiento ----
	"W01": {
		Desc:    "Un inicio suave: respiración, alargamiento de la columna y postura.",
		HowTo:   []string{"Ponte de pie, pies al ancho de caderas.", "Al inspirar, estírate suavemente hacia arriba desde la coronilla.", "Puedes subir los brazos por los lados.", "Al espirar, baja los hombros y relaja el cuello."},
		Correct: []string{"Pies firmes en el suelo.", "Los hombros no suben a las orejas.", "Cuello largo.", "Respiración tranquila."},
		Wrong:   []string{"Echar la cabeza atrás.", "Arquear de más la zona lumbar.", "Subir los hombros.", "Aguantar la respiración."},
		Voice:   Voice{Start: "Ponte recto. Respira con calma.", Mid: []string{"Estírate desde la coronilla."}, Finish: "Hombros abajo. Sigue."},
	},
	"W02": {
		Desc:    "Movilizar el cuello antes del entrenamiento.",
		HowTo:   []string{"Ponte de pie.", "Gira la cabeza despacio a la derecha.", "Vuelve al centro.", "Gira la cabeza a la izquierda."},
		Correct: []string{"Movimiento lento.", "Los hombros se quedan abajo.", "El tronco no gira.", "Rango cómodo."},
		Wrong:   []string{"Movimientos bruscos.", "Echar la cabeza atrás.", "Subir los hombros.", "Estirar el cuello hasta el dolor."},
		Voice:   Voice{Start: "Giramos la cabeza.", Mid: []string{"Suave, sin tirones."}, Finish: "Cabeza al centro."},
	},
	"W03": {
		Desc:    "Calentar las articulaciones de los hombros y la espalda alta.",
		HowTo:   []string{"Ponte de pie.", "Sube un poco los hombros.", "Llévalos atrás.", "Bájalos y repite el círculo."},
		Correct: []string{"Los hombros se mueven fluidos.", "Brazos relajados.", "El cuello queda libre.", "Tronco estable."},
		Wrong:   []string{"Sacudir los hombros.", "Encorvarse.", "Tensar el cuello.", "Rango demasiado amplio."},
		Voice:   Voice{Start: "Círculos de hombros, atrás.", Mid: []string{"Cuello libre."}, Finish: "Baja los hombros."},
	},
	"W04": {
		Desc:    "Más movilidad para hombros y espalda alta.",
		HowTo:   []string{"Ponte de pie.", "Gira los hombros hacia delante.", "Mantén el cuello libre.", "No balancees el tronco."},
		Correct: []string{"Movimiento controlado.", "Hombros sin tensión.", "Respiración regular.", "El tronco no se balancea."},
		Wrong:   []string{"Hombros a las orejas.", "Movimiento brusco.", "Redondear la espalda.", "Aguantar la respiración."},
		Voice:   Voice{Start: "Círculos hacia delante.", Mid: []string{"No tenses el cuello."}, Finish: "Relaja los hombros."},
	},
	"W05": {
		Desc:    "Calentar hombros, deltoides y espalda alta.",
		HowTo:   []string{"Brazos a los lados, a la altura de los hombros.", "Pequeños círculos hacia delante.", "Mantén los hombros abajo.", "No aguantes la respiración."},
		Correct: []string{"Círculos pequeños.", "Brazos a la altura de los hombros.", "Cuello relajado.", "El tronco no se balancea."},
		Wrong:   []string{"Grandes vaivenes.", "Hombros a las orejas.", "Arquear la espalda.", "Tensar el cuello."},
		Voice:   Voice{Start: "Brazos a los lados. Círculos pequeños.", Mid: []string{"Hombros abajo."}, Finish: "Baja los brazos."},
	},
	"W06": {
		Desc:    "Calentar los hombros y los estabilizadores de la escápula.",
		HowTo:   []string{"Brazos a los lados.", "Pequeños círculos hacia atrás.", "No subas los hombros.", "Mantén el tronco recto."},
		Correct: []string{"Movimiento corto.", "Hombros abajo.", "Las escápulas trabajan suaves.", "Respiración tranquila."},
		Wrong:   []string{"Sacudidas.", "Vaivenes amplios.", "Encorvarse.", "Tensar el cuello."},
		Voice:   Voice{Start: "Círculos hacia atrás.", Mid: []string{"Rango pequeño."}, Finish: "Relaja los brazos."},
	},
	"W07": {
		Desc:    "Activa la espalda alta y abre el pecho.",
		HowTo:   []string{"Ponte de pie.", "Lleva los brazos un poco atrás.", "Junta suavemente las escápulas.", "Vuelve a la posición neutra."},
		Correct: []string{"El pecho se abre.", "Hombros abajo.", "Las escápulas trabajan suaves.", "La espalda no se arquea."},
		Wrong:   []string{"Quebrar la espalda hacia atrás.", "Levantar el mentón.", "Tirar de los brazos.", "Subir los hombros."},
		Voice:   Voice{Start: "Abrimos el pecho.", Mid: []string{"Escápulas suavemente atrás."}, Finish: "Vuelve al centro."},
	},
	"W08": {
		Desc:    "Movilidad suave para la columna dorsal y el tronco.",
		HowTo:   []string{"Ponte de pie.", "Gira el tronco a la derecha.", "Vuelve al centro.", "Gira el tronco a la izquierda."},
		Correct: []string{"El movimiento sale del tronco.", "Las caderas casi quietas.", "Los pies no giran.", "Rango cómodo."},
		Wrong:   []string{"Girar el tronco con brusquedad.", "Torcer las rodillas.", "Sacudir los pies.", "Caer hacia atrás."},
		Voice:   Voice{Start: "Giros de tronco.", Mid: []string{"Pies firmes."}, Finish: "Vuelve al centro."},
	},
	"W09": {
		Desc:    "Calienta la cadera y la parte posterior de la pierna; enseña a flexionar sin redondear la espalda.",
		HowTo:   []string{"Ponte de pie, rodillas algo blandas.", "Lleva la cadera hacia atrás.", "Flexiona el tronco con la espalda recta.", "Vuelve a subir."},
		Correct: []string{"Espalda plana.", "El movimiento empieza en la cadera.", "Rodillas algo blandas.", "El cuello sigue la línea de la espalda."},
		Wrong:   []string{"Redondear la espalda.", "Convertirlo en sentadilla.", "Forzar el alcance hacia abajo.", "Levantar la cabeza."},
		Voice:   Voice{Start: "Cadera atrás, espalda recta.", Mid: []string{"No redondees la espalda."}, Finish: "Incorpórate con calma."},
	},
	"W10": {
		Desc:    "Calentar pies, gemelos y equilibrio.",
		HowTo:   []string{"Ponte de pie.", "Súbete de puntillas.", "Mantén un instante.", "Baja despacio."},
		Correct: []string{"Cuerpo vertical.", "Movimiento fluido.", "Pies firmes.", "Las rodillas no caen hacia dentro."},
		Wrong:   []string{"Dejar caer los talones.", "Balancearse.", "Caer sobre el borde externo del pie.", "Hacer tirones."},
		Voice:   Voice{Start: "Súbete de puntillas.", Mid: []string{"Baja despacio."}, Finish: "Pies firmes."},
	},

	// ---- Bloque principal ----
	"M01": {
		Desc:      "Ejercicio básico para pecho, tríceps, hombros y tronco.",
		HowTo:     []string{"Manos bajo los hombros o algo más anchas.", "Piernas extendidas, cuerpo recto.", "Baja despacio.", "Empuja hacia arriba sin tirones."},
		Correct:   []string{"Cuerpo recto.", "Abdomen firme.", "Los codos no se abren del todo.", "Movimiento controlado."},
		Wrong:     []string{"Hundir la zona lumbar.", "Levantar la cadera.", "Dejarse caer.", "Abrir los codos a 90°."},
		Breathing: "Inspira al bajar, espira al subir.",
		Voice:     Voice{Start: "Cuerpo recto. Empezamos.", Mid: []string{"Abdomen firme.", "Codos no muy abiertos."}, Finish: "Listo. Relaja los hombros."},
	},
	"M02": {
		Desc:      "Una variante de flexión con más trabajo de tríceps.",
		HowTo:     []string{"Manos casi bajo los hombros.", "Codos hacia atrás, pegados al cuerpo.", "Baja despacio.", "Empuja sin tirones."},
		Correct:   []string{"Cuerpo recto.", "Los codos no se abren.", "Hombros sin tensión.", "Muñecas sin dolor."},
		Wrong:     []string{"Poner las manos muy juntas.", "Doblar las muñecas.", "Abrir los codos.", "Perder la línea del cuerpo."},
		Breathing: "Inspira al bajar, espira al subir.",
		Safety:    "Si duelen codos o muñecas, pasa a flexión normal con menos repeticiones.",
		Voice:     Voice{Start: "Flexión cerrada. Codos pegados.", Mid: []string{"Sin presionar las muñecas.", "Cuerpo recto."}, Finish: "Bien. Relaja los hombros."},
	},
	"M03": {
		Desc:      "Flexión con control en el punto más bajo.",
		HowTo:     []string{"Ponte en posición de flexión.", "Baja despacio.", "Mantén 1 segundo.", "Empuja hacia arriba."},
		Correct:   []string{"Pausa controlada.", "El cuerpo no se hunde.", "Codos bajo control.", "Sin caídas."},
		Wrong:     []string{"Dejarse caer.", "Relajarse abajo.", "Aguantar la respiración.", "Arquear la zona lumbar."},
		Breathing: "Inspira, pausa corta, espira al subir.",
		Voice:     Voice{Start: "Baja despacio. Mantén abajo.", Mid: []string{"No caigas, controla.", "La zona lumbar no se hunde."}, Finish: "Genial. Descansa."},
	},
	"C01": {
		Desc:    "Ejercicio para el abdomen y el control de la pelvis.",
		HowTo:   []string{"Túmbate boca arriba.", "Presiona la zona lumbar contra la esterilla.", "Levanta las piernas.", "Cruza con rango corto."},
		Correct: []string{"Espalda en la esterilla.", "Piernas no muy bajas.", "Cuello relajado.", "Movimiento controlado."},
		Wrong:   []string{"Despegar la espalda.", "Bajar mucho las piernas.", "Tirar del cuello hacia delante.", "Vaivenes bruscos."},
		Safety:  "Si la espalda se despega, pasa a Toe taps o Dead bug.",
		Voice:   Voice{Start: "Tijeras. Espalda presionada.", Mid: []string{"Sube las piernas si tira la espalda.", "Cuello relajado."}, Last: "Cinco segundos.", Finish: "Baja las piernas despacio."},
	},
	"C02": {
		Desc:      "Ejercicio estático para abdomen, hombros, glúteos y estabilidad del tronco.",
		HowTo:     []string{"Apóyate en codos y puntas de los pies.", "Codos bajo los hombros.", "Aprieta abdomen y glúteos.", "Mantén una línea recta del cuerpo."},
		Correct:   []string{"Hombros sobre los codos.", "La cadera no se hunde.", "Abdomen firme.", "Mirada al suelo."},
		Wrong:     []string{"Hundir la zona lumbar.", "Subir la cadera como un techo.", "Mirar al frente.", "Aguantar la respiración."},
		Breathing: "Inspira corto, espira largo y tranquilo.",
		Voice:     Voice{Start: "Plancha. Cuerpo en una línea.", Mid: []string{"Abdomen firme.", "La espalda no se hunde."}, Last: "Cinco segundos.", Finish: "Baja las rodillas."},
	},
	"C03": {
		Desc:    "Ejercicio para el abdomen y el control de la zona lumbar.",
		HowTo:   []string{"Túmbate boca arriba.", "Presiona la zona lumbar contra la esterilla.", "Levanta las piernas.", "Movimientos cortos arriba y abajo alternados."},
		Correct: []string{"Espalda estable.", "Rango corto.", "Piernas no muy bajas.", "Respiración regular."},
		Wrong:   []string{"Arquear la zona lumbar.", "Grandes vaivenes.", "Tensar el cuello.", "Aguantar la respiración."},
		Safety:  "Si la espalda se despega, sube las piernas o pasa a Dead bug.",
		Voice:   Voice{Start: "Espalda presionada.", Mid: []string{"Rango corto.", "Respira de forma regular."}, Last: "Cinco segundos.", Finish: "Baja las piernas despacio."},
	},
	"C04": {
		Desc:      "Ejercicio seguro para el tronco profundo y la estabilidad.",
		HowTo:     []string{"Boca arriba, brazos hacia arriba.", "Rodillas a 90°.", "Baja despacio el brazo y la pierna contrarios.", "Vuelve y repite en el otro lado."},
		Correct:   []string{"Espalda presionada.", "Movimiento lento.", "El tronco no se balancea.", "Rango bajo control."},
		Wrong:     []string{"Despegar la espalda.", "Moverse rápido.", "Bajar mucho la pierna.", "Perder el control de la pelvis."},
		Breathing: "Espira al estirar el brazo y la pierna.",
		Voice:     Voice{Start: "Dead bug. Espalda presionada.", Mid: []string{"Muévete despacio.", "El tronco no se balancea."}, Finish: "Bien. Recoge las piernas."},
	},
	"C05": {
		Desc:    "Ejercicio para el abdomen lateral y la estabilidad.",
		HowTo:   []string{"Túmbate de lado.", "Codo bajo el hombro.", "Levanta la cadera.", "Mantén el cuerpo en una línea."},
		Correct: []string{"Codo bajo el hombro.", "Cadera levantada.", "El cuerpo no se inclina.", "Cuello neutro."},
		Wrong:   []string{"Hundir la cadera.", "Pegar el hombro a la oreja.", "Girar el tronco hacia abajo.", "Aguantar la respiración."},
		Safety:  "Si duele el hombro, reduce el tiempo a la mitad o haz plancha normal.",
		Voice:   Voice{Start: "Plancha lateral. Codo bajo el hombro.", Mid: []string{"Mantén la cadera arriba.", "Cuello libre."}, Last: "Cinco segundos.", Finish: "Baja con suavidad."},
	},
	"C06": {
		Desc:    "Ejercicio de control para el abdomen; más suave que las tijeras.",
		HowTo:   []string{"Boca arriba, piernas a 90°.", "Baja un talón despacio al suelo.", "Vuelve la pierna.", "Repite con la otra pierna."},
		Correct: []string{"La espalda no se despega.", "Movimiento lento.", "Pelvis estable.", "El talón toca suave."},
		Wrong:   []string{"Dejar caer la pierna.", "Arquear la zona lumbar.", "Mover las dos piernas a la vez.", "Apresurarse."},
		Voice:   Voice{Start: "Toe taps. Despacio.", Mid: []string{"Espalda en la esterilla.", "Toque suave."}, Finish: "Relaja el abdomen."},
	},
	"C07": {
		Desc:    "Ejercicio estático para el abdomen y el control del tronco.",
		HowTo:   []string{"Boca arriba, espalda presionada.", "Levanta un poco los hombros.", "Piernas flexionadas o algo elevadas.", "Mantén la posición."},
		Correct: []string{"Espalda en el suelo.", "Abdomen firme.", "El cuello no se proyecta.", "Sin aguantar la respiración."},
		Wrong:   []string{"Arquear la zona lumbar.", "Levantar el mentón.", "Piernas muy bajas.", "Aguantar el dolor de espalda."},
		Safety:  "Si tira la espalda, flexiona las rodillas o pasa a Dead bug.",
		Voice:   Voice{Start: "Hollow hold. Espalda presionada.", Mid: []string{"Respira de forma regular.", "Si tira la espalda, flexiona las rodillas."}, Last: "Cinco segundos.", Finish: "Baja hombros y piernas."},
	},
	"C08": {
		Desc:      "Plancha corta e intensa con máxima tensión del tronco.",
		HowTo:     []string{"Ponte en plancha sobre antebrazos.", "Codos bajo los hombros.", "Aprieta abdomen y glúteos.", "Lleva los codos hacia las puntas de los pies."},
		Correct:   []string{"Tensión abdominal fuerte.", "Glúteos activos.", "Cuerpo recto.", "Respira sin aguantar."},
		Wrong:     []string{"Mantener como plancha floja.", "Hundir la zona lumbar.", "Aguantar la respiración.", "Mantener demasiado tiempo."},
		Breathing: "Respiraciones cortas, sin aguantar.",
		Safety:    "Si es muy duro, plancha normal de 45 a 60 segundos.",
		Voice:     Voice{Start: "Aprieta abdomen y glúteos.", Mid: []string{"Codos hacia las puntas.", "Todo el cuerpo firme."}, Last: "Cinco segundos.", Finish: "Baja las rodillas."},
	},
	"B01": {
		Desc:    "Ejercicio para la espalda, los glúteos y la cadena posterior.",
		HowTo:   []string{"Túmbate boca abajo.", "Brazos al frente o junto al cuerpo.", "Levanta un poco el pecho y las piernas.", "Baja con control."},
		Correct: []string{"Elevación pequeña.", "El cuello sigue la línea de la espalda.", "Glúteos algo activos.", "Sin tirones."},
		Wrong:   []string{"Quebrar fuerte la espalda.", "Levantar la cabeza.", "Subir mucho las piernas.", "Hacer tirones."},
		Voice:   Voice{Start: "Barca. Elevación pequeña.", Mid: []string{"Cuello neutro.", "No quiebres la espalda."}, Finish: "Baja con suavidad."},
	},
	"B02": {
		Desc:    "Ejercicio para la espalda alta, las escápulas y el hombro posterior.",
		HowTo:   []string{"Túmbate boca abajo.", "Levanta un poco el pecho o déjalo en el suelo.", "Lleva los brazos en arco por encima de la cabeza.", "Devuelve los brazos."},
		Correct: []string{"Cuello relajado.", "Las escápulas trabajan.", "Rango cómodo.", "Sin sobrecargar la espalda."},
		Wrong:   []string{"Levantar la cabeza.", "Arquearse de más.", "Tirar de los brazos.", "Hombros a las orejas."},
		Voice:   Voice{Start: "Brazos en arco. Cabeza abajo.", Mid: []string{"Las escápulas trabajan.", "No tenses el cuello."}, Finish: "Relaja los brazos."},
	},
	"B03": {
		Desc:    "Sostén estático para la espalda y los glúteos.",
		HowTo:   []string{"Túmbate boca abajo.", "Levanta un poco el pecho y las piernas.", "Mantén la posición.", "Respira de forma regular."},
		Correct: []string{"Elevación moderada.", "Cuello neutro.", "Glúteos activos.", "Respiración regular."},
		Wrong:   []string{"Levantar la cabeza.", "Arquearse fuerte.", "Aguantar la respiración.", "Aguantar el dolor de espalda."},
		Safety:  "Si la espalda molesta, haz Barca con menos rango.",
		Voice:   Voice{Start: "Mantén la barca.", Mid: []string{"Respira de forma regular.", "Cuello largo."}, Last: "Cinco segundos.", Finish: "Baja con suavidad."},
	},
	"B04": {
		Desc:    "Ejercicio para la espalda alta, las escápulas y el hombro posterior.",
		HowTo:   []string{"Túmbate boca abajo.", "Flexiona los brazos en forma de 'W'.", "Levanta un poco codos y manos.", "Junta las escápulas y baja."},
		Correct: []string{"Movimiento pequeño.", "Las escápulas trabajan.", "La cabeza mira al suelo.", "Hombros lejos de las orejas."},
		Wrong:   []string{"Levantar la cabeza.", "Subir mucho los brazos.", "Tensar el cuello.", "Arquear la zona lumbar."},
		Voice:   Voice{Start: "Elevación en W. Escápulas atrás.", Mid: []string{"Cabeza abajo.", "Movimiento pequeño."}, Finish: "Baja los brazos."},
	},
	"B05": {
		Desc:    "Ejercicio para la espalda alta, los hombros y el trapecio inferior.",
		HowTo:   []string{"Túmbate boca abajo.", "Estira los brazos en diagonal en forma de 'Y'.", "Levanta un poco los brazos del suelo.", "Baja de nuevo."},
		Correct: []string{"Los brazos suben poco.", "Escápulas abajo y atrás.", "Cuello neutro.", "Espalda tranquila."},
		Wrong:   []string{"Balanceo brusco.", "Levantar la cabeza.", "Hombros a las orejas.", "Arquearse fuerte."},
		Voice:   Voice{Start: "Elevación en Y. Brazos en diagonal.", Mid: []string{"Hombros lejos de las orejas.", "Elevación pequeña."}, Finish: "Relaja la espalda."},
	},
	"G01": {
		Desc:    "Ejercicio para glúteos, parte posterior de la pierna y estabilidad pélvica.",
		HowTo:   []string{"Boca arriba, rodillas flexionadas.", "Pies en el suelo.", "Levanta la cadera hacia arriba.", "Arriba aprieta los glúteos y baja despacio."},
		Correct: []string{"Empuje desde los talones.", "Cadera hasta una línea recta.", "Los glúteos trabajan.", "La espalda no se sobreextiende."},
		Wrong:   []string{"Arquear la espalda arriba.", "Pies muy juntos.", "Levantar los talones.", "Subir la cadera de un tirón."},
		Voice:   Voice{Start: "Puente. Empuja desde los talones.", Mid: []string{"Arriba aprieta los glúteos.", "No arquees la espalda."}, Finish: "Baja la cadera despacio."},
	},
	"G02": {
		Desc:    "Puente de glúteos con sostén arriba.",
		HowTo:   []string{"Levanta la cadera hacia arriba.", "Mantén arriba.", "Aprieta los glúteos.", "Baja despacio."},
		Correct: []string{"Sostén estable.", "Glúteos activos.", "Las costillas no salen.", "Bajada lenta."},
		Wrong:   []string{"Sobreextender la espalda.", "Perder los pies.", "Dejar caer la cadera.", "Aguantar la respiración."},
		Voice:   Voice{Start: "Puente con sostén. Arriba y mantén.", Mid: []string{"Los glúteos trabajan.", "Baja despacio."}, Finish: "Relaja las piernas."},
	},
	"L01": {
		Desc:    "Sentadilla poco profunda para piernas y glúteos con poca carga en la rodilla.",
		HowTo:   []string{"Pies algo más anchos que las caderas.", "Lleva la cadera hacia atrás.", "Flexiona las rodillas poco.", "Sube desde los pies."},
		Correct: []string{"Poca profundidad.", "Rodillas en dirección a los dedos.", "Talones en el suelo.", "Espalda plana."},
		Wrong:   []string{"Bajar demasiado.", "Dejar caer las rodillas hacia dentro.", "Levantar los talones.", "Dejarse caer."},
		Safety:  "Si duele la rodilla, pasa enseguida al puente de glúteos.",
		Voice:   Voice{Start: "Mini sentadilla. Poco profunda.", Mid: []string{"Cadera atrás.", "Rodillas hacia los dedos."}, Finish: "Bien. No bajes mucho."},
	},
	"A01": {
		Desc:    "Ejercicio de bíceps sin material: un brazo opone resistencia.",
		HowTo:   []string{"Flexiona por el codo el brazo que trabaja.", "Con la otra mano presiona hacia abajo el antebrazo.", "El brazo que trabaja sube despacio.", "Mantén la resistencia todo el recorrido."},
		Correct: []string{"Movimiento lento.", "Resistencia que se nota.", "Codo pegado al cuerpo.", "El hombro no sube."},
		Wrong:   []string{"Hacerlo sin resistencia.", "Tirar del brazo.", "Subir el hombro.", "Aguantar la respiración."},
		Voice:   Voice{Start: "Bíceps. Un brazo opone resistencia.", Mid: []string{"Sube despacio.", "Mantén la resistencia."}, Finish: "Cambia de brazo."},
	},
	"A02": {
		Desc:    "Sostén estático de bíceps sin material.",
		HowTo:   []string{"Flexiona a unos 90° el brazo que trabaja.", "Con la otra mano presiona hacia abajo.", "El brazo que trabaja opone resistencia.", "Mantén la tensión sin moverte."},
		Correct: []string{"Codo a unos 90°.", "Tensión estable.", "Hombros abajo.", "Respiración regular."},
		Wrong:   []string{"Presionar a tirones.", "Aguantar la respiración.", "Subir el hombro.", "Torcer el tronco."},
		Voice:   Voice{Start: "Sostén de bíceps. Presiona uno contra otro.", Mid: []string{"Hombros abajo.", "Respira, no aguantes."}, Last: "Cinco segundos.", Finish: "Cambia de brazo."},
	},
	"S01": {
		Desc:    "Ejercicio para hombros, deltoides y espalda alta.",
		HowTo:   []string{"Abre los brazos a la altura de los hombros.", "Haz círculos pequeños.", "Mantén los hombros abajo.", "Mantén el tronco recto."},
		Correct: []string{"Rango pequeño.", "Brazos estables.", "Cuello relajado.", "Respiración regular."},
		Wrong:   []string{"Grandes vaivenes.", "Tensar el cuello.", "Subir los hombros.", "Arquear la espalda."},
		Voice:   Voice{Start: "Círculos pequeños de brazos.", Mid: []string{"Hombros abajo.", "Círculos pequeños."}, Last: "Cinco segundos.", Finish: "Baja los brazos."},
	},

	// ---- Vuelta a la calma ----
	"CD01": {
		Desc:    "Bajar el pulso y relajarse tras el entrenamiento.",
		HowTo:   []string{"Túmbate boca arriba.", "Relaja los hombros.", "Inspira con calma.", "Espira despacio."},
		Correct: []string{"Respiración tranquila.", "Hombros relajados.", "El abdomen se mueve suave.", "Sin tensión en el cuello."},
		Wrong:   []string{"Aguantar la respiración.", "Tensar la cara.", "Arquear la espalda.", "Apresurarse."},
		Voice:   Voice{Start: "Respira con calma.", Mid: []string{"Espira largo."}, Finish: "Pasamos a los estiramientos."},
	},
	"CD02": {
		Desc:    "Abrir suavemente el pecho y la parte anterior del hombro.",
		HowTo:   []string{"Túmbate boca arriba.", "Abre los brazos a los lados.", "Relaja los hombros.", "Respira con calma."},
		Correct: []string{"El pecho se abre suave.", "Hombros sin tensión.", "Espalda tranquila.", "Sin dolor de hombro."},
		Wrong:   []string{"Tirar de los brazos hasta el dolor.", "Arquear la espalda.", "Subir los hombros.", "Aguantar la respiración."},
		Voice:   Voice{Start: "Brazos a los lados. Pecho abierto.", Mid: []string{"No estires hasta el dolor."}, Finish: "Vuelve los brazos despacio."},
	},
	"CD03": {
		Desc:    "Estiramiento suave del tronco y la zona dorsolumbar.",
		HowTo:   []string{"Boca arriba, rodillas flexionadas.", "Baja las rodillas suavemente a un lado.", "Deja los hombros en la esterilla.", "Repite al otro lado."},
		Correct: []string{"Movimiento suave.", "Los hombros no se levantan.", "Sin dolor de espalda.", "Respiración regular."},
		Wrong:   []string{"Forzar las rodillas al suelo.", "Giro brusco.", "Levantar un hombro.", "Aguantar el dolor."},
		Voice:   Voice{Start: "Rodillas suavemente a un lado.", Mid: []string{"Hombros en el suelo."}, Finish: "Vuelve por el centro."},
	},
	"CD04": {
		Desc:    "Estiramiento suave de la parte posterior de la pierna tras la carga.",
		HowTo:   []string{"Boca arriba, levanta una pierna.", "Sujeta el muslo o la espinilla.", "Lleva la pierna suavemente hacia ti.", "Repite con la otra pierna."},
		Correct: []string{"La rodilla puede ir algo flexionada.", "Espalda tranquila.", "Estiramiento suave.", "Respiración regular."},
		Wrong:   []string{"Tirar de la pierna con fuerza.", "Llevar el pie a la cara.", "Levantar la cadera.", "Aguantar el dolor tras la rodilla."},
		Voice:   Voice{Start: "Levanta la pierna. Tira suave.", Mid: []string{"No hasta el dolor."}, Finish: "Cambia de lado con suavidad."},
	},
	"CD05": {
		Desc:    "Estiramiento de la zona glútea y la parte posterior de la pelvis.",
		HowTo:   []string{"Túmbate boca arriba.", "Apoya un pie sobre el otro muslo.", "Lleva el muslo suavemente hacia ti.", "No presiones la rodilla."},
		Correct: []string{"Sensación en el glúteo.", "La rodilla no duele.", "Espalda tranquila.", "Movimiento suave."},
		Wrong:   []string{"Presionar la rodilla con la mano.", "Forzar hasta el dolor.", "Torcer la pelvis.", "Aguantar la respiración."},
		Safety:  "Si la rodilla molesta, haz un estiramiento de glúteo suave tumbado.",
		Voice:   Voice{Start: "Figura cuatro. No presiones la rodilla.", Mid: []string{"Lleva suave hacia ti."}, Finish: "Cambia de lado con suavidad."},
	},
	"CD06": {
		Desc:    "Abrir suavemente la parte anterior del cuerpo y la columna dorsal.",
		HowTo:   []string{"Túmbate boca abajo.", "Apoya los antebrazos en el suelo.", "Levanta suavemente el pecho.", "Mantén el cuello largo."},
		Correct: []string{"Elevación suave.", "Codos bajo los hombros o algo delante.", "Hombros sin tensión.", "Espalda sin dolor."},
		Wrong:   []string{"Echar la cabeza atrás.", "Arquearse de más.", "Tensar los hombros.", "Aguantar el dolor de espalda."},
		Voice:   Voice{Start: "Postura de esfinge. Elevación suave.", Mid: []string{"Cuello largo."}, Finish: "Baja a la esterilla."},
	},
}
